"""ArchetypeRegistry — the process-wide singleton that hands out ArchetypeProfile.

Lookup order for ``ArchetypeRegistry.get(code)``:

1. **Catalog module** — ``app.archetypes.catalog.<code>.PROFILE`` (generated by
   ``scripts/archetypes/generate_catalog.py``). This is the canonical source.
2. **Legacy loader** — ``app.archetypes.loader.build_profile_from_legacy(code)``
   which synthesizes a profile by reading ``client_generator`` dicts and the
   md prompts on disk. Used while the catalog is still being populated.
3. **Fallback** — ``app.archetypes.fallback.neutral_profile(code)`` returns a
   valid but uninteresting ``ArchetypeProfile`` so consumers never crash.

All three paths return an ``ArchetypeProfile``. ``strict=True`` raises
``ArchetypeNotFoundError`` instead of falling through.

Design rules:
- No imports from ``app.services`` at module load time — ``loader`` does the
  late imports lazily so that ``from app.archetypes import ArchetypeRegistry``
  is cheap.
- Cache the resolved profile in a dict so the second lookup is O(1).
- Thread-safety via ``threading.RLock`` (Registry is shared across request tasks).
"""

from __future__ import annotations

import importlib
import logging
import threading
from typing import Iterable

from app.archetypes.profile import ArchetypeProfile

logger = logging.getLogger(__name__)

_LOCK = threading.RLock()
_CACHE: dict[str, ArchetypeProfile] = {}
_FALLBACK_HITS: dict[str, int] = {}


class ArchetypeNotFoundError(KeyError):
    """Raised by ``Registry.get(code, strict=True)`` when the code is unknown."""


class ArchetypeRegistry:
    """Singleton lookup for ``ArchetypeProfile``. All methods are classmethods
    so there is no ``__init__`` to call — use ``ArchetypeRegistry.get(...)``."""

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @classmethod
    def get(cls, code: str, *, strict: bool = False) -> ArchetypeProfile:
        """Return the ArchetypeProfile for ``code`` (e.g. ``"skeptic"``).

        With ``strict=False`` (default) the Registry always returns a profile
        — falling back to legacy data or a neutral profile rather than raising.
        This keeps every existing call-site working while we migrate data.

        With ``strict=True`` a missing code raises ``ArchetypeNotFoundError``.
        """

        with _LOCK:
            cached = _CACHE.get(code)
            if cached is not None:
                return cached

            profile = cls._resolve(code, strict=strict)
            _CACHE[code] = profile
            return profile

    @classmethod
    def all_codes(cls) -> list[str]:
        """Return every archetype code known to the enum (authoritative list)."""

        # Late import: ``models.roleplay`` pulls in SQLAlchemy mappings which
        # we don't want at package import time.
        from app.models.roleplay import ArchetypeCode

        return [code.value for code in ArchetypeCode]

    @classmethod
    def iter_profiles(cls) -> Iterable[ArchetypeProfile]:
        """Yield the ArchetypeProfile for every known code, resolving on demand.

        Useful for admin/wiki endpoints that list everything.
        """

        for code in cls.all_codes():
            yield cls.get(code)

    @classmethod
    def register(cls, profile: ArchetypeProfile) -> None:
        """Inject a profile into the cache manually — intended for tests."""

        with _LOCK:
            _CACHE[profile.code] = profile

    @classmethod
    def clear_cache(cls) -> None:
        """Drop all cached profiles. Tests use this between fixtures."""

        with _LOCK:
            _CACHE.clear()
            _FALLBACK_HITS.clear()

    @classmethod
    def fallback_hits(cls) -> dict[str, int]:
        """Return a snapshot of how many times each code hit the fallback path.

        Operations monitoring — should be ``{}`` in production after
        ``catalog/`` is fully populated. A warning is logged each time a new
        archetype falls through so we can track the migration."""

        with _LOCK:
            return dict(_FALLBACK_HITS)

    # ------------------------------------------------------------------
    # Internal resolution
    # ------------------------------------------------------------------

    @classmethod
    def _resolve(cls, code: str, *, strict: bool) -> ArchetypeProfile:
        # Phase 1: catalog may be empty initially, loader handles everything.
        if catalog := _try_catalog(code):
            return catalog

        if legacy := _try_legacy(code):
            _FALLBACK_HITS[code] = _FALLBACK_HITS.get(code, 0) + 1
            if _FALLBACK_HITS[code] == 1:
                logger.info(
                    "ArchetypeRegistry: using legacy loader for %r (catalog miss). "
                    "Re-run scripts/archetypes/generate_catalog.py when ready.",
                    code,
                )
            return legacy

        if strict:
            raise ArchetypeNotFoundError(f"No archetype profile for code {code!r}")

        _FALLBACK_HITS[code] = _FALLBACK_HITS.get(code, 0) + 1
        if _FALLBACK_HITS[code] == 1:
            logger.warning(
                "ArchetypeRegistry: neutral fallback for unknown code %r. "
                "Either add it to catalog/ or extend client_generator dicts.",
                code,
            )
        from app.archetypes.fallback import neutral_profile

        return neutral_profile(code)


def _try_catalog(code: str) -> ArchetypeProfile | None:
    """Import ``app.archetypes.catalog.<code>``; return its ``PROFILE`` constant."""

    module_path = f"app.archetypes.catalog.{code}"
    try:
        module = importlib.import_module(module_path)
    except ModuleNotFoundError:
        return None
    except Exception as exc:  # pragma: no cover — defensive: broken catalog entry
        logger.error(
            "ArchetypeRegistry: failed to import %s: %s", module_path, exc,
            exc_info=True,
        )
        return None

    profile = getattr(module, "PROFILE", None)
    if isinstance(profile, ArchetypeProfile):
        return profile
    logger.error(
        "ArchetypeRegistry: %s imported but PROFILE missing/wrong type (%r)",
        module_path, type(profile).__name__,
    )
    return None


def _try_legacy(code: str) -> ArchetypeProfile | None:
    """Synthesize a profile from legacy client_generator dicts."""

    from app.archetypes.loader import build_profile_from_legacy

    try:
        return build_profile_from_legacy(code)
    except Exception as exc:  # pragma: no cover — defensive
        logger.warning(
            "ArchetypeRegistry: legacy loader failed for %r: %s", code, exc,
        )
        return None
