"""One-shot codegen: write app/archetypes/catalog/<code>.py for every archetype.

Data source: ``app.archetypes.loader.build_profile_from_legacy`` — the same
function Registry uses as fallback. Running this script snapshots the legacy
dicts into concrete, editable Python modules. From that point on each file is
the source of truth for its archetype; editing ARCHETYPE_OCEAN etc. won't
change behaviour (unless you rerun codegen).

Invariants the script preserves:
- Files are deterministic for the same legacy input (sorted keys, stable
  formatting) — re-running on unchanged input produces zero diff.
- Group and prompt paths match what the loader computes.
- ``__init__.py`` is never overwritten.
- Unknown/invalid codes are skipped with a warning — they'd just be neutral
  profiles, no point codegen'ing those.

Usage:
    python -m scripts.archetypes.generate_catalog               # write all
    python -m scripts.archetypes.generate_catalog --check       # exit-1 on diff
    python -m scripts.archetypes.generate_catalog --only skeptic aggressive

Once catalog/ is populated, commit the generated files. Subsequent hand-edits
to individual catalog files take precedence and should NOT be overwritten by
regenerating blindly — use --check in CI to detect unintentional drift.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
from textwrap import indent


TEMPLATE = '''"""AUTO-GENERATED ArchetypeProfile for code ``{code}``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code={code!r},
    group=ArchetypeGroup.{group_name},
    title_ru={title_ru!r},
    ocean_base=OceanRange(
        openness={O},
        conscientiousness={C},
        extraversion={E},
        agreeableness={A},
        neuroticism={N},
    ),
    pad_anchor=PadAnchor(
        pleasure={P},
        arousal={A_pad},
        dominance={D},
    ),
    fears=[
{fears_block}
    ],
    soft_spots=[
{soft_block}
    ],
    breaking_points=[
{breaking_block}
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path={prompt_v1},
    prompt_v2_path={prompt_v2},
    emotion_profile_slug={emotion_slug!r},
    difficulty_tier={tier!r},
)
'''


def _fmt_list(items: list[str]) -> str:
    if not items:
        return ""
    lines = [f"        {item!r}," for item in items]
    return "\n".join(lines)


def _fmt_path(path) -> str:
    """Emit a portable `_prompt("...")` call or ``None``."""

    if path is None:
        return "None"
    # Path must already be inside prompts/characters/ for this to work.
    return f"_prompt({path.name!r})"


def _render_module(profile) -> str:
    pad = profile.pad_anchor
    return TEMPLATE.format(
        code=profile.code,
        group_name=profile.group.name,
        title_ru=profile.title_ru,
        O=profile.ocean_base.openness,
        C=profile.ocean_base.conscientiousness,
        E=profile.ocean_base.extraversion,
        A=profile.ocean_base.agreeableness,
        N=profile.ocean_base.neuroticism,
        P=pad.pleasure,
        A_pad=pad.arousal,
        D=pad.dominance,
        fears_block=_fmt_list(profile.fears),
        soft_block=_fmt_list(profile.soft_spots),
        breaking_block=_fmt_list(profile.breaking_points),
        prompt_v1=_fmt_path(profile.prompt_v1_path),
        prompt_v2=_fmt_path(profile.prompt_v2_path),
        emotion_slug=profile.emotion_profile_slug,
        tier=profile.difficulty_tier,
    )


def _iter_targets(only: list[str] | None) -> list[str]:
    from app.archetypes.registry import ArchetypeRegistry

    codes = ArchetypeRegistry.all_codes()
    if only:
        bad = set(only) - set(codes)
        if bad:
            print(f"ERROR: unknown codes in --only: {sorted(bad)}", file=sys.stderr)
            raise SystemExit(2)
        return sorted(only)
    return sorted(codes)


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 on any drift from current files")
    ap.add_argument("--only", nargs="+", metavar="CODE",
                    help="limit to specific codes")
    args = ap.parse_args(argv)

    from app.archetypes.loader import build_profile_from_legacy

    catalog_dir = Path(__file__).resolve().parents[2] / "app" / "archetypes" / "catalog"
    catalog_dir.mkdir(parents=True, exist_ok=True)

    targets = _iter_targets(args.only)
    drift: list[str] = []
    written = 0
    skipped = 0

    for code in targets:
        profile = build_profile_from_legacy(code)
        if profile is None:
            print(f"skip {code} (legacy loader returned None)")
            skipped += 1
            continue
        content = _render_module(profile)
        path = catalog_dir / f"{code}.py"
        existing = path.read_text(encoding="utf-8") if path.exists() else ""

        if args.check:
            if existing != content:
                drift.append(code)
                for line in difflib.unified_diff(
                    existing.splitlines(), content.splitlines(),
                    fromfile=f"{code}.py (current)",
                    tofile=f"{code}.py (would-generate)",
                    lineterm="",
                ):
                    print(line)
        else:
            if existing != content:
                path.write_text(content, encoding="utf-8")
                print(f"wrote {path.relative_to(catalog_dir.parent.parent)}")
                written += 1
            else:
                skipped += 1

    if args.check:
        if drift:
            print(f"\nDRIFT in {len(drift)} codes: {drift}")
            return 1
        print(f"no drift in {len(targets)} codes")
        return 0

    print(f"\ndone: {written} written, {skipped} skipped ({len(targets)} total)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
