"""AUTO-GENERATED ArchetypeProfile for code ``aggressive``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='aggressive',
    group=ArchetypeGroup.RESISTANCE,
    title_ru='Агрессор',
    ocean_base=OceanRange(
        openness=0.3,
        conscientiousness=0.25,
        extraversion=0.7,
        agreeableness=0.1,
        neuroticism=0.8,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.3,
        arousal=0.7,
        dominance=0.6,
    ),
    fears=[
        'Навязывают ненужные услуги',
        'Хотят заработать на моей беде',
        'Могу справиться сам, без юристов',
        'Банки специально запугивают',
        'Государство на стороне банков',
        'Суд всегда против должника',
    ],
    soft_spots=[
        'В глубине души боится за семью',
        'Хочет доказать что может решить проблему',
        'Злится на себя, а не на менеджера',
    ],
    breaking_points=[
        'Не бойтесь моего напора',
        'Ответьте фактами',
        'Признайте моё право злиться',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=_prompt('aggressive_v1.md'),
    prompt_v2_path=_prompt('aggressive_v2.md'),
    emotion_profile_slug='aggressive',
    difficulty_tier='intermediate',
)
