"""AUTO-GENERATED ArchetypeProfile for code ``ashamed``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='ashamed',
    group=ArchetypeGroup.EMOTIONAL,
    title_ru='Ashamed',
    ocean_base=OceanRange(
        openness=0.3,
        conscientiousness=0.6,
        extraversion=0.2,
        agreeableness=0.65,
        neuroticism=0.75,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.6,
        arousal=0.3,
        dominance=-0.6,
    ),
    fears=[
        'Все узнают, что я банкрот',
        'Дети будут стыдиться',
        'На работе узнают — позор',
        'Соседи увидят объявление в газете',
        'Это клеймо на всю жизнь',
        'Я сам виноват в долгах',
    ],
    soft_spots=[
        'Хочет снять груз стыда',
        'Мечтает рассказать правду близким',
        'Готов на всё ради чистой совести',
    ],
    breaking_points=[
        'Гарантируйте конфиденциальность',
        'Скажите что это нормально',
        'Никто не узнает',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('ashamed_v2.md'),
    emotion_profile_slug='ashamed',
    difficulty_tier='beginner',
)
