"""AUTO-GENERATED ArchetypeProfile for code ``avoidant``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='avoidant',
    group=ArchetypeGroup.AVOIDANCE,
    title_ru='Avoidant',
    ocean_base=OceanRange(
        openness=0.3,
        conscientiousness=0.35,
        extraversion=0.25,
        agreeableness=0.55,
        neuroticism=0.65,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.4,
        arousal=-0.2,
        dominance=-0.3,
    ),
    fears=[
        'Не хочу думать об этом сейчас',
        'Может, долги просто спишут сами',
        'Процедура слишком сложная',
        'Придётся ходить по инстанциям',
        'Не хочу никого видеть по этому поводу',
        'Лучше просто не брать трубку',
    ],
    soft_spots=[
        'Хочет чтобы проблема исчезла',
        'Устал прятаться от звонков',
        'Тайно ищет решение',
    ],
    breaking_points=[
        'Минимум усилий с моей стороны',
        'Всё можно сделать удалённо',
        'Не нужно никуда ходить',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('avoidant_v2.md'),
    emotion_profile_slug='avoidant',
    difficulty_tier='beginner',
)
