"""AUTO-GENERATED ArchetypeProfile for code ``couple``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='couple',
    group=ArchetypeGroup.SPECIAL,
    title_ru='Couple',
    ocean_base=OceanRange(
        openness=0.5,
        conscientiousness=0.5,
        extraversion=0.6,
        agreeableness=0.4,
        neuroticism=0.6,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.3,
        arousal=0.3,
        dominance=0.0,
    ),
    fears=[
        'Муж/жена против банкротства',
        'Мы не можем договориться между собой',
        'Один хочет, другой нет',
        'А совместное имущество не пострадает?',
        'Супруг(а) боится больше меня',
        'Нам нужно обоим быть на консультации',
    ],
    soft_spots=[
        'Хотят сохранить семью',
        'За конфликтом — общая цель',
        'Нуждаются в медиаторе',
    ],
    breaking_points=[
        'Успокойте обоих',
        'Покажите что это общее решение',
        'Выгода для двоих',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('couple_v2.md'),
    emotion_profile_slug='couple',
    difficulty_tier='beginner',
)
