"""AUTO-GENERATED ArchetypeProfile for code ``crying``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='crying',
    group=ArchetypeGroup.EMOTIONAL,
    title_ru='Плачущий',
    ocean_base=OceanRange(
        openness=0.3,
        conscientiousness=0.35,
        extraversion=0.3,
        agreeableness=0.6,
        neuroticism=0.9,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.9,
        arousal=0.6,
        dominance=-0.8,
    ),
    fears=[
        'Не могу перестать плакать от стресса',
        'Ночью не сплю, думаю о долгах',
        'Дети видят, что мне плохо',
        'Чувствую себя полным неудачником',
        'Стыдно просить о помощи',
        'Муж/жена не знает, как мне плохо',
    ],
    soft_spots=[
        'Хочет чтобы кто-то просто выслушал',
        'Нуждается в эмоциональной поддержке',
        'За слезами — сила',
    ],
    breaking_points=[
        'Просто выслушайте',
        'Скажите что всё будет хорошо',
        'Дайте время прийти в себя',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('crying_v2.md'),
    emotion_profile_slug='crying',
    difficulty_tier='beginner',
)
