"""AUTO-GENERATED ArchetypeProfile for code ``desperate``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='desperate',
    group=ArchetypeGroup.EMOTIONAL,
    title_ru='Отчаявшийся',
    ocean_base=OceanRange(
        openness=0.25,
        conscientiousness=0.25,
        extraversion=0.45,
        agreeableness=0.5,
        neuroticism=0.85,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.8,
        arousal=0.7,
        dominance=-0.7,
    ),
    fears=[
        'Мне конец, уже нечем платить',
        'Приставы придут на следующей неделе',
        'Не могу купить ребёнку еду',
        'Думал(а) о самом плохом',
        'Звонят каждый день, больше не могу',
        'Последний шанс — если не поможете, не знаю что делать',
    ],
    soft_spots=[
        'Любой шанс — последний',
        'Готов на всё ради семьи',
        'Хочет верить что выход есть',
    ],
    breaking_points=[
        'Скажите что выход есть',
        'Начните прямо сейчас',
        'Помогите с первым шагом бесплатно',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('desperate_v2.md'),
    emotion_profile_slug='desperate',
    difficulty_tier='beginner',
)
