"""AUTO-GENERATED ArchetypeProfile for code ``grateful``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='grateful',
    group=ArchetypeGroup.EMOTIONAL,
    title_ru='Благодарный',
    ocean_base=OceanRange(
        openness=0.55,
        conscientiousness=0.55,
        extraversion=0.55,
        agreeableness=0.85,
        neuroticism=0.25,
    ),
    pad_anchor=PadAnchor(
        pleasure=0.4,
        arousal=0.1,
        dominance=-0.2,
    ),
    fears=[
        'Так рад(а), что кто-то наконец помогает',
        'Спасибо что выслушали',
        'Надеюсь, вы действительно можете помочь',
        'Друг посоветовал — он вам доверяет',
        'Боюсь, что ожидания не оправдаются',
        'Готов(а) делать всё что скажете',
    ],
    soft_spots=[
        'Хочет отблагодарить тех кто помогает',
        'Ценит человеческое отношение',
        'Готов рекомендовать друзьям',
    ],
    breaking_points=[
        'Покажите конкретный план',
        'Объясните что ожидать',
        'Дайте контакт юриста',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('grateful_v2.md'),
    emotion_profile_slug='grateful',
    difficulty_tier='beginner',
)
