"""AUTO-GENERATED ArchetypeProfile for code ``hostile``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='hostile',
    group=ArchetypeGroup.RESISTANCE,
    title_ru='Враждебный',
    ocean_base=OceanRange(
        openness=0.2,
        conscientiousness=0.2,
        extraversion=0.75,
        agreeableness=0.05,
        neuroticism=0.9,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.5,
        arousal=0.8,
        dominance=0.5,
    ),
    fears=[
        'Все мошенники, никому нельзя верить',
        'Менеджер — обманщик, как все',
        'Государство создало эту ситуацию',
        'Меня уже обманывали десять раз',
        'Зачем мне ваши услуги — ещё денег вытянуть',
        'Я лучше буду должен, чем платить юристам',
    ],
    soft_spots=[
        'За маской злости — страх',
        'Когда-то кому-то доверял',
        'Хочет быть услышанным',
    ],
    breaking_points=[
        'Не сдавайтесь когда я ругаюсь',
        'Покажите реальные результаты',
        'Будьте честны до конца',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('hostile_v2.md'),
    emotion_profile_slug='hostile',
    difficulty_tier='intermediate',
)
