"""AUTO-GENERATED ArchetypeProfile for code ``know_it_all``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='know_it_all',
    group=ArchetypeGroup.CONTROL,
    title_ru='Всезнайка',
    ocean_base=OceanRange(
        openness=0.65,
        conscientiousness=0.7,
        extraversion=0.6,
        agreeableness=0.15,
        neuroticism=0.5,
    ),
    pad_anchor=PadAnchor(
        pleasure=0.1,
        arousal=0.2,
        dominance=0.6,
    ),
    fears=[
        'Я сам юрист, знаю всё лучше вас',
        'Читал закон — там всё по-другому',
        'Ваша информация устарела',
        'Знакомый юрист сказал, что это не работает',
        'Вы не знаете последних изменений в законе',
        'Я проверю каждое ваше слово',
    ],
    soft_spots=[
        'Хочет чтобы признали его экспертизу',
        'Уважает тех кто знает больше',
        'Боится выглядеть глупо',
    ],
    breaking_points=[
        'Процитируйте статью точнее чем я',
        'Покажите знание деталей',
        'Дайте новую информацию',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('know_it_all_v2.md'),
    emotion_profile_slug='know_it_all',
    difficulty_tier='advanced',
)
