"""AUTO-GENERATED ArchetypeProfile for code ``lawyer_client``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='lawyer_client',
    group=ArchetypeGroup.CONTROL,
    title_ru='Клиент-юрист',
    ocean_base=OceanRange(
        openness=0.6,
        conscientiousness=0.9,
        extraversion=0.5,
        agreeableness=0.2,
        neuroticism=0.35,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.2,
        arousal=0.2,
        dominance=0.4,
    ),
    fears=[
        'Мой юрист сказал что это не поможет',
        'Я проверю ваши слова у своего адвоката',
        'Знаю свои права — не надо мне рассказывать',
        'Какая у вас лицензия?',
        'Ваш управляющий в реестре ЕФРСБ?',
        'Покажите договор перед разговором',
    ],
    soft_spots=[
        'Хочет профессионала одного уровня',
        'За критикой — уважение к знаниям',
        'Готов платить за экспертизу',
    ],
    breaking_points=[
        'Покажите экспертизу на моём уровне',
        'Знание последних поправок',
        'Реестр ЕФРСБ',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('lawyer_client_v2.md'),
    emotion_profile_slug='lawyer_client',
    difficulty_tier='advanced',
)
