"""AUTO-GENERATED ArchetypeProfile for code ``lawyer_level_2``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='lawyer_level_2',
    group=ArchetypeGroup.COGNITIVE,
    title_ru='Lawyer Level 2',
    ocean_base=OceanRange(
        openness=0.65,
        conscientiousness=0.6,
        extraversion=0.55,
        agreeableness=0.2,
        neuroticism=0.55,
    ),
    pad_anchor=PadAnchor(
        pleasure=0.0,
        arousal=0.0,
        dominance=0.0,
    ),
    fears=[

    ],
    soft_spots=[

    ],
    breaking_points=[

    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=None,
    emotion_profile_slug='lawyer_level_2',
    difficulty_tier='intermediate',
)
