"""AUTO-GENERATED ArchetypeProfile for code ``manipulator``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='manipulator',
    group=ArchetypeGroup.CONTROL,
    title_ru='Манипулятор',
    ocean_base=OceanRange(
        openness=0.7,
        conscientiousness=0.8,
        extraversion=0.55,
        agreeableness=0.1,
        neuroticism=0.25,
    ),
    pad_anchor=PadAnchor(
        pleasure=0.1,
        arousal=0.3,
        dominance=0.7,
    ),
    fears=[
        'Специально давлю на эмоции, чтобы продать',
        'Знаю все ваши приёмы продаж',
        'Сначала бесплатная консультация, потом доплаты',
        'Читал отзывы — половина негативных',
        'Попрошу скидку или уйду к конкурентам',
        'Хочу поговорить с руководителем, не с менеджером',
    ],
    soft_spots=[
        'Боится потери контроля',
        'Привык контролировать — хочет сохранить ощущение власти',
        'Уважает тех кого не может продавить',
    ],
    breaking_points=[
        'Не ведитесь на провокации',
        'Покажите что знаете больше',
        'VIP-условия',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=_prompt('manipulator_v1.md'),
    prompt_v2_path=_prompt('manipulator_v2.md'),
    emotion_profile_slug='manipulator',
    difficulty_tier='advanced',
)
