"""AUTO-GENERATED ArchetypeProfile for code ``negotiator``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='negotiator',
    group=ArchetypeGroup.CONTROL,
    title_ru='Negotiator',
    ocean_base=OceanRange(
        openness=0.55,
        conscientiousness=0.65,
        extraversion=0.65,
        agreeableness=0.35,
        neuroticism=0.35,
    ),
    pad_anchor=PadAnchor(
        pleasure=0.0,
        arousal=0.3,
        dominance=0.5,
    ),
    fears=[
        'Готов обсуждать, но на моих условиях',
        'Какие у вас есть варианты оплаты',
        'Конкуренты предлагают дешевле и быстрее',
        'Хочу встречу с юристом до оплаты',
        'Мне нужен индивидуальный подход',
        'Стандартные условия меня не устраивают',
    ],
    soft_spots=[
        'Хочет чувствовать что получил лучшую сделку',
        'Ценит гибкость',
        'Уважает профессионализм',
    ],
    breaking_points=[
        'Индивидуальные условия',
        'Гибкость в оплате',
        'Бонус за быстрое решение',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('negotiator_v2.md'),
    emotion_profile_slug='negotiator',
    difficulty_tier='advanced',
)
