"""AUTO-GENERATED ArchetypeProfile for code ``overwhelmed``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='overwhelmed',
    group=ArchetypeGroup.EMOTIONAL,
    title_ru='Overwhelmed',
    ocean_base=OceanRange(
        openness=0.35,
        conscientiousness=0.3,
        extraversion=0.4,
        agreeableness=0.55,
        neuroticism=0.8,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.7,
        arousal=0.5,
        dominance=-0.6,
    ),
    fears=[
        'Слишком много всего навалилось',
        'Не понимаю с чего начать',
        'Голова идёт кругом от информации',
        'Не могу сосредоточиться',
        'Забываю половину того что мне говорят',
        'Каждый день новая проблема',
    ],
    soft_spots=[
        'Хочет простой пошаговый план',
        'Нуждается в структуре',
        'Благодарен за терпение',
    ],
    breaking_points=[
        'Разбейте на маленькие шаги',
        'Один шаг за раз',
        'Напомните позже',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('overwhelmed_v2.md'),
    emotion_profile_slug='overwhelmed',
    difficulty_tier='beginner',
)
