"""AUTO-GENERATED ArchetypeProfile for code ``paranoid``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='paranoid',
    group=ArchetypeGroup.AVOIDANCE,
    title_ru='Paranoid',
    ocean_base=OceanRange(
        openness=0.25,
        conscientiousness=0.65,
        extraversion=0.35,
        agreeableness=0.15,
        neuroticism=0.85,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.6,
        arousal=0.5,
        dominance=0.1,
    ),
    fears=[
        'Это схема по выкачиванию денег',
        'Мои данные продадут мошенникам',
        'Управляющий работает на банк',
        'Суд подкуплен кредиторами',
        'Записывают звонок для использования против меня',
        'Откуда они знают мой номер и долги',
    ],
    soft_spots=[
        'В глубине души хочет довериться',
        'Устал от постоянного напряжения',
        'Хочет найти «своего» специалиста',
    ],
    breaking_points=[
        'Покажите лицензии и сертификаты',
        'Дайте номер дела для проверки',
        'Прозрачность на каждом этапе',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('paranoid_v2.md'),
    emotion_profile_slug='paranoid',
    difficulty_tier='beginner',
)
