"""AUTO-GENERATED ArchetypeProfile for code ``passive``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='passive',
    group=ArchetypeGroup.AVOIDANCE,
    title_ru='Пассивный',
    ocean_base=OceanRange(
        openness=0.3,
        conscientiousness=0.3,
        extraversion=0.2,
        agreeableness=0.75,
        neuroticism=0.55,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.3,
        arousal=-0.3,
        dominance=-0.5,
    ),
    fears=[
        'Всё равно ничего не поможет',
        'Уже пробовали — не получилось',
        'Ситуация безнадёжная',
        'Нет сил разбираться с бумагами',
        'Потеряю последнее, что есть',
        'Слишком поздно что-то менять',
    ],
    soft_spots=[
        'Втайне надеется что кто-то поможет',
        'Устал нести груз один',
        'Мечтает начать жизнь с чистого листа',
    ],
    breaking_points=[
        'Предложите сделать первый шаг за меня',
        'Скажите что нужна одна подпись',
        'Покажите что другие справились',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=_prompt('passive_v1.md'),
    prompt_v2_path=_prompt('passive_v2.md'),
    emotion_profile_slug='passive',
    difficulty_tier='beginner',
)
