"""AUTO-GENERATED ArchetypeProfile for code ``pragmatic``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='pragmatic',
    group=ArchetypeGroup.CONTROL,
    title_ru='Прагматик',
    ocean_base=OceanRange(
        openness=0.5,
        conscientiousness=0.75,
        extraversion=0.45,
        agreeableness=0.5,
        neuroticism=0.3,
    ),
    pad_anchor=PadAnchor(
        pleasure=0.0,
        arousal=0.1,
        dominance=0.4,
    ),
    fears=[
        'Стоимость услуг не окупится',
        'Можно разобраться самому через МФЦ',
        'Нет гарантий результата',
        'Сроки затянутся на годы',
        'Скрытые платежи и доплаты',
        'Конкуренты предлагают дешевле',
    ],
    soft_spots=[
        'Готов платить если увидит конкретный план',
        'Ценит экспертизу и цифры',
        'Хочет понять ROI от банкротства',
    ],
    breaking_points=[
        'Точные цифры экономии',
        'Сравнение стоимости vs продолжения выплат',
        'Чёткий таймлайн',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=_prompt('pragmatic_v1.md'),
    prompt_v2_path=_prompt('pragmatic_v2.md'),
    emotion_profile_slug='pragmatic',
    difficulty_tier='advanced',
)
