"""AUTO-GENERATED ArchetypeProfile for code ``referred``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='referred',
    group=ArchetypeGroup.SPECIAL,
    title_ru='Referred',
    ocean_base=OceanRange(
        openness=0.55,
        conscientiousness=0.5,
        extraversion=0.5,
        agreeableness=0.7,
        neuroticism=0.3,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.1,
        arousal=0.1,
        dominance=0.0,
    ),
    fears=[
        'Друг/подруга посоветовал(а) вашу компанию',
        'Знакомый сказал что помогли',
        'Пришёл по рекомендации, но всё равно осторожен',
        'Мне обещали индивидуальный подход',
        'Ожидаю такой же сервис, как рассказали',
        'Если обманете — весь офис узнает',
    ],
    soft_spots=[
        'Доверяет мнению друга',
        'Готов к действию',
        'Хочет подтвердить ожидания',
    ],
    breaking_points=[
        'Подтвердите отзыв друга',
        'Покажите аналогичное дело',
        'Персональный менеджер',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('referred_v2.md'),
    emotion_profile_slug='referred',
    difficulty_tier='beginner',
)
