"""AUTO-GENERATED ArchetypeProfile for code ``returner``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='returner',
    group=ArchetypeGroup.SPECIAL,
    title_ru='Returner',
    ocean_base=OceanRange(
        openness=0.45,
        conscientiousness=0.55,
        extraversion=0.45,
        agreeableness=0.4,
        neuroticism=0.6,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.3,
        arousal=0.2,
        dominance=0.0,
    ),
    fears=[
        'В прошлый раз не сложилось',
        'Поменял компанию — стало только хуже',
        'Боюсь, что опять потеряю время и деньги',
        'Уже слышал все обещания',
        'Хочу гарантий, что в этот раз получится',
        'Раньше другой менеджер обещал то же самое',
    ],
    soft_spots=[
        'Хочет верить что в этот раз получится',
        'Знает чего не хочет',
        'Опыт — сила',
    ],
    breaking_points=[
        'Объясните что изменилось с прошлого раза',
        'Гарантия результата',
        'Другой подход',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('returner_v2.md'),
    emotion_profile_slug='returner',
    difficulty_tier='beginner',
)
