"""AUTO-GENERATED ArchetypeProfile for code ``rushed``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='rushed',
    group=ArchetypeGroup.SPECIAL,
    title_ru='Rushed',
    ocean_base=OceanRange(
        openness=0.4,
        conscientiousness=0.7,
        extraversion=0.65,
        agreeableness=0.35,
        neuroticism=0.45,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.2,
        arousal=0.6,
        dominance=0.3,
    ),
    fears=[
        'У меня пять минут, говорите быстро',
        'Я в машине, давайте по существу',
        'Перезвоните через час, сейчас совещание',
        'Быстро: сколько стоит и сколько по времени?',
        'Мне некогда ездить к вам в офис',
        'Можно всё сделать удалённо?',
    ],
    soft_spots=[
        'За спешкой — реальная проблема',
        'Ценит эффективность',
        'Уважает тех кто не тратит время',
    ],
    breaking_points=[
        'Уложитесь в 3 минуты',
        'Конкретные цифры без воды',
        'Всё удалённо',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('rushed_v2.md'),
    emotion_profile_slug='rushed',
    difficulty_tier='beginner',
)
