"""AUTO-GENERATED ArchetypeProfile for code ``sarcastic``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='sarcastic',
    group=ArchetypeGroup.RESISTANCE,
    title_ru='Sarcastic',
    ocean_base=OceanRange(
        openness=0.55,
        conscientiousness=0.45,
        extraversion=0.5,
        agreeableness=0.2,
        neuroticism=0.6,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.1,
        arousal=0.3,
        dominance=0.3,
    ),
    fears=[
        'Конечно, всё решится одним звонком',
        'Юристы — святые люди, бесплатно работают',
        'Судья прочитает мою историю и заплачет',
        'Банки просто простят всё из доброты',
        'Очередной «спаситель» с волшебной таблеткой',
        'Наверное, вы звоните мне из альтруизма',
    ],
    soft_spots=[
        'За иронией — глубокая боль',
        'Ценит остроумных людей',
        'Уважает тех кто не обижается',
    ],
    breaking_points=[
        'Отвечайте юмором',
        'Не обижайтесь',
        'Покажите что вы тоже человек',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('sarcastic_v2.md'),
    emotion_profile_slug='sarcastic',
    difficulty_tier='intermediate',
)
