"""AUTO-GENERATED ArchetypeProfile for code ``shopper``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='shopper',
    group=ArchetypeGroup.CONTROL,
    title_ru='Shopper',
    ocean_base=OceanRange(
        openness=0.6,
        conscientiousness=0.55,
        extraversion=0.5,
        agreeableness=0.45,
        neuroticism=0.4,
    ),
    pad_anchor=PadAnchor(
        pleasure=0.0,
        arousal=0.2,
        dominance=0.3,
    ),
    fears=[
        'Сейчас обзваниваю пять компаний',
        'У конкурентов дешевле на 30%',
        'Не буду решать сегодня — мне нужно сравнить',
        'А что входит в эту цену?',
        'Есть бесплатные консультации у других',
        'Скидку на второе обращение дадите?',
    ],
    soft_spots=[
        'Ищет лучшее соотношение цена/качество',
        'Устал от сравнений',
        'Хочет наконец принять решение',
    ],
    breaking_points=[
        'Лучшая цена с обоснованием',
        'Всё включено без доплат',
        'Гарантия возврата',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=None,
    prompt_v2_path=_prompt('shopper_v2.md'),
    emotion_profile_slug='shopper',
    difficulty_tier='advanced',
)
