"""AUTO-GENERATED ArchetypeProfile for code ``skeptic``.

Generated by ``scripts/archetypes/generate_catalog.py`` on first migration.
After initial codegen, hand-edit this file freely to refine the profile —
the generator will flag drift via ``--check`` instead of overwriting.
"""

from pathlib import Path

from app.archetypes.profile import (
    ArchetypeGroup,
    ArchetypeProfile,
    OceanRange,
    PadAnchor,
)

# Resolve prompt paths relative to the api package root. This keeps catalog
# modules portable across machines (no hard-coded absolute paths in git).
# parents[0] = catalog/, parents[1] = archetypes/, parents[2] = app/,
# parents[3] = api/, where ``prompts/characters/`` lives next to ``app``.
_PROMPTS_DIR = Path(__file__).resolve().parents[3] / "prompts" / "characters"


def _prompt(name: str) -> Path | None:
    """Return ``_PROMPTS_DIR/<name>`` iff the file actually exists."""

    p = _PROMPTS_DIR / name
    return p if p.is_file() else None


PROFILE = ArchetypeProfile(
    code='skeptic',
    group=ArchetypeGroup.RESISTANCE,
    title_ru='Скептик',
    ocean_base=OceanRange(
        openness=0.45,
        conscientiousness=0.65,
        extraversion=0.4,
        agreeableness=0.3,
        neuroticism=0.55,
    ),
    pad_anchor=PadAnchor(
        pleasure=-0.2,
        arousal=0.1,
        dominance=0.3,
    ),
    fears=[
        'Обманут с документами и заберут квартиру',
        'Юристы — мошенники, деньги возьмут и пропадут',
        'Где-то есть подвох, слишком хорошо звучит',
        'После банкротства не дадут кредит 10 лет',
        'Коллекторы станут звонить ещё чаще',
        'Испортят кредитную историю навсегда',
    ],
    soft_spots=[
        'Хочет защитить семью от приставов',
        'Устал от постоянных звонков коллекторов',
        'Боится потерять единственное жильё',
    ],
    breaking_points=[
        'Покажите конкретное судебное решение',
        'Назовите точную статью закона',
        'Дайте письменную гарантию',
    ],
    default_goals=[],
    default_objections=[],
    prompt_v1_path=_prompt('skeptic_v1.md'),
    prompt_v2_path=_prompt('skeptic_v2.md'),
    emotion_profile_slug='skeptic',
    difficulty_tier='intermediate',
)
