"""
Game Director Engine — Central Orchestrator for Hunter888 v5.

This is the BRAIN of the entire narrative game system.
It connects all 8 agents into a unified story flow:

  Agent 1 (Roleplay) ←→ Game Director ←→ Agent 3 (Traps)
  Agent 2 (Scoring)  ←→ Game Director ←→ Agent 4 (Voice)
  Agent 5 (Gamification) ←→ Game Director ←→ Agent 6 (Generator)
  Agent 7 (CRM)      ←→ Game Director ←→ Agent 8 (PvP)

Data flow:
  1. Manager starts session → GD loads ClientStory from DB
  2. GD builds context injection (3-tier) → injected into LLM prompt
  3. During session: stage directions analyzed for consequences
  4. After session: GD advances story, evaluates storylets, generates events
  5. Between calls: GD generates frontend panel events

All inter-agent communication flows through this module.
Agents do NOT import each other — they import game_director.
"""

import logging
import uuid
from datetime import datetime, timedelta
from dataclasses import dataclass, field
from typing import Optional

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.roleplay import (
    ClientStory,
    PersonalityProfile,
    EpisodicMemory,
)
from app.models.game_crm import GameClientEvent, GameEventType
from app.models.training import TrainingSession

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════
# DATA CONTRACTS (used by all agents)
# ═══════════════════════════════════════════════════════════

# Lifecycle states for the narrative state machine (between calls)
LIFECYCLE_STATES = [
    "NEW_LEAD", "FIRST_CONTACT", "INTERESTED", "OBJECTING",
    "THINKING", "CALLBACK_SCHEDULED", "FOLLOW_UP_CALL",
    "MEETING_SET", "DEAL_CLOSED", "REJECTED", "GHOSTING",
    "NO_ANSWER", "REACTIVATION",
]

# Allowed transitions: {from_state: [to_states]}
LIFECYCLE_TRANSITIONS = {
    "NEW_LEAD": ["FIRST_CONTACT"],
    "FIRST_CONTACT": ["INTERESTED", "REJECTED", "CALLBACK_SCHEDULED", "NO_ANSWER"],
    "INTERESTED": ["MEETING_SET", "THINKING", "OBJECTING"],
    "OBJECTING": ["INTERESTED", "REJECTED", "CALLBACK_SCHEDULED"],
    "THINKING": ["CALLBACK_SCHEDULED", "GHOSTING", "INTERESTED"],
    "CALLBACK_SCHEDULED": ["FOLLOW_UP_CALL", "NO_ANSWER", "GHOSTING"],
    "FOLLOW_UP_CALL": ["MEETING_SET", "OBJECTING", "REJECTED"],
    "MEETING_SET": ["DEAL_CLOSED", "REJECTED", "NO_ANSWER"],
    "DEAL_CLOSED": [],  # terminal
    "REJECTED": ["REACTIVATION"],
    "GHOSTING": ["REACTIVATION"],
    "NO_ANSWER": ["FIRST_CONTACT", "GHOSTING"],
    "REACTIVATION": ["INTERESTED", "REJECTED"],
}

# Consequence levels
CONSEQUENCE_COSMETIC = "cosmetic"
CONSEQUENCE_LOCAL = "local"
CONSEQUENCE_GLOBAL = "global"

# Relationship score modifiers
REL_PROMISE_KEPT = 5
REL_EMPATHY_DETECTED = 3
REL_PROMISE_BROKEN = -10
REL_RUDENESS = -15
REL_FORGOT_CLIENT = -5
REL_PERFECT_CALL = 10


@dataclass
class ConsequenceEvent:
    """Consequence generated by agent actions, processed by Game Director."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    level: str = CONSEQUENCE_LOCAL  # cosmetic | local | global
    trigger_action: str = ""
    effect_description: str = ""
    applied_at: datetime = field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None
    is_active: bool = True
    source_agent: str = ""  # "agent_1", "agent_3", etc.


@dataclass
class StoryletActivation:
    """A storylet that has been activated for a client."""
    storylet_code: str = ""
    narrative_text: str = ""
    effects: dict = field(default_factory=dict)
    priority: int = 5
    activated_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class BetweenCallEvent:
    """Event generated between calls for the frontend panel."""
    event_type: str = "message"  # message | status_change | consequence | storylet | callback
    title: str = ""
    content: str = ""
    game_timestamp: datetime = field(default_factory=datetime.utcnow)
    payload: dict = field(default_factory=dict)


@dataclass
class ContextInjection:
    """Three-tier context assembled for LLM prompt injection."""
    tier1_identity: str = ""    # archetype + emotion + personality + factors (~500 tokens)
    tier2_memory: str = ""      # past calls + consequences + promises (~800 tokens)
    tier3_situational: str = "" # storylets + events + reputation (~400 tokens)
    total_tokens: int = 0
    active_factors: list = field(default_factory=list)
    active_storylets: list = field(default_factory=list)
    active_consequences: list = field(default_factory=list)


@dataclass
class SessionResult:
    """Result of a completed training session, sent by Agent 1."""
    session_id: str = ""
    client_story_id: str = ""
    final_emotion_state: str = "cold"
    score_total: float = 0.0
    score_breakdown: dict = field(default_factory=dict)
    traps_fell: list = field(default_factory=list)
    traps_dodged: list = field(default_factory=list)
    promises_made: list = field(default_factory=list)
    promises_broken: list = field(default_factory=list)
    key_moments: list = field(default_factory=list)
    stage_directions: list = field(default_factory=list)
    duration_seconds: int = 0
    empathy_detected: bool = False
    rudeness_detected: bool = False
    legal_errors: list = field(default_factory=list)


# ═══════════════════════════════════════════════════════════
# STORYLET TEMPLATES (BFL Domain)
# ═══════════════════════════════════════════════════════════

STORYLET_TEMPLATES = [
    {
        "code": "wife_found_out",
        "preconditions": {"lifecycle_state": "THINKING", "min_days_in_state": 3, "family_status": "married", "min_debt": 300_000},
        "narrative": "Жена клиента узнала о долгах. Она в ярости и напугана. Клиент под двойным давлением — от кредиторов и от семьи.",
        "effects": {"activate_factors": ["anxiety", "social_fear"], "arousal_delta": 0.5},
        "priority": 8,
        "cooldown_days": 30,
    },
    {
        "code": "collectors_arrived",
        "preconditions": {"lifecycle_state": "GHOSTING", "min_days_in_state": 7, "min_debt": 500_000},
        "narrative": "Коллекторы пришли домой к клиенту. Клиент в панике и готов разговаривать, но доверие на нуле.",
        "effects": {"force_state": "REACTIVATION", "pleasure_delta": -0.8, "arousal_delta": 0.9, "activate_factors": ["distrust"]},
        "priority": 9,
        "cooldown_days": 60,
    },
    {
        "code": "friend_recommended_lawyer",
        "preconditions": {"min_calls": 2, "manager_never_mentioned_bankruptcy": True},
        "narrative": "Друг клиента порекомендовал конкурирующего юриста. Клиент теперь имеет альтернативу.",
        "effects": {"activate_factors": ["competitiveness"], "add_objection_chain": "competitor_comparison"},
        "priority": 6,
        "cooldown_days": 20,
    },
    {
        "code": "court_order_received",
        "preconditions": {"lifecycle_state": "REJECTED", "min_days_in_state": 30, "min_debt": 2_000_000},
        "narrative": "Клиент получил судебный приказ. Ситуация стала срочной.",
        "effects": {"force_state": "REACTIVATION", "activate_factors": ["anger", "anxiety"], "urgency": True},
        "priority": 10,
        "cooldown_days": 90,
    },
    {
        "code": "salary_garnishment",
        "preconditions": {"lifecycle_state": "GHOSTING", "min_days_in_state": 14, "min_debt": 500_000},
        "narrative": "С зарплаты клиента удерживают 50%. Финансовое отчаяние достигло пика.",
        "effects": {"force_state": "INTERESTED", "pleasure_delta": -1.0, "dominance_delta": -0.8},
        "priority": 9,
        "cooldown_days": 60,
    },
    {
        "code": "positive_precedent",
        "preconditions": {"lifecycle_state": "THINKING", "manager_cited_law_articles": True},
        "narrative": "Клиент прочитал про успешное дело о банкротстве в интернете. Надежда выросла.",
        "effects": {"relationship_delta": 10, "activate_factors": ["curiosity", "optimism"]},
        "priority": 5,
        "cooldown_days": 15,
    },
    {
        "code": "job_loss",
        "preconditions": {"min_difficulty": 7, "lifecycle_state": "THINKING", "min_days_in_state": 5},
        "narrative": "Клиент потерял работу. Финансовая ситуация резко ухудшилась.",
        "effects": {"activate_factors": ["anxiety", "pessimism"], "debt_pressure_delta": 0.3},
        "priority": 7,
        "cooldown_days": 30,
    },
    {
        "code": "bank_restructuring_offer",
        "preconditions": {"lifecycle_state": "OBJECTING", "min_calls": 3, "max_debt": 1_000_000},
        "narrative": "Банк предложил реструктуризацию. Клиент рассматривает альтернативу банкротству.",
        "effects": {"activate_factors": ["competitiveness"], "add_objection_chain": "bank_alternative"},
        "priority": 6,
        "cooldown_days": 20,
    },
]


# ═══════════════════════════════════════════════════════════
# CORE ENGINE
# ═══════════════════════════════════════════════════════════

class GameDirectorEngine:
    """
    Central orchestrator. All inter-agent data flows through here.

    Usage by agents:
        from app.services.game_director import game_director
        # Agent 1: get context for LLM prompt
        ctx = await game_director.build_context_injection(story_id, db)
        # Agent 1: report session result
        await game_director.advance_story(session_result, db)
        # Agent 3: report trap consequence
        await game_director.apply_consequence(consequence, db)
        # Agent 7: get pending events
        events = await game_director.get_pending_events(story_id, db)
    """

    # ─── STORY LIFECYCLE ────────────────────────────────

    async def create_story(
        self,
        user_id: str,
        scenario_code: str,
        personality_profile: dict,
        difficulty: int,
        db: AsyncSession,
    ) -> ClientStory:
        """Create a new ClientStory. Called when manager starts a multi-call arc."""
        story = ClientStory(
            id=str(uuid.uuid4()),
            user_id=user_id,
            lifecycle_state="NEW_LEAD",
            total_calls=0,
            relationship_score=50.0,
            personality_profile=personality_profile,
            memory={"promises": [], "key_moments": [], "insults": [], "agreements": []},
            active_storylets=[],
            consequence_log=[],
            difficulty=difficulty,
            scenario_code=scenario_code,
        )
        db.add(story)
        await db.flush()
        logger.info(f"Created ClientStory {story.id} for user {user_id}")
        return story

    async def load_story(self, story_id: str, db: AsyncSession) -> Optional[ClientStory]:
        """Load a ClientStory from DB. Cached in Redis for 24h by caller."""
        result = await db.execute(select(ClientStory).where(ClientStory.id == story_id))
        return result.scalar_one_or_none()

    # ─── CONTEXT INJECTION (for Agent 1 / LLM) ─────────

    async def build_context_injection(
        self, story_id: str, db: AsyncSession
    ) -> ContextInjection:
        """
        Assemble 3-tier context from memory, consequences, storylets.
        Called by Agent 1 before each call via build_multi_call_prompt().
        Token budget: ~1700 total (500 + 800 + 400).
        """
        story = await self.load_story(story_id, db)
        if not story:
            return ContextInjection()

        ctx = ContextInjection()

        # Tier 1: Identity Core (always injected, ~500 tokens)
        profile = story.personality_profile or {}
        ocean = profile.get("ocean", {})
        pad = profile.get("pad", {})
        factors = profile.get("human_factors", [])
        active_factors = [f for f in factors if f.get("active", False)]

        ctx.tier1_identity = self._build_tier1(story, ocean, pad, active_factors)
        ctx.active_factors = active_factors

        # Tier 2: Story Memory (if calls > 1, ~800 tokens)
        if story.total_calls > 0:
            ctx.tier2_memory = await self._build_tier2(story, db)

        # Tier 3: Situational (storylets + events, ~400 tokens)
        ctx.tier3_situational = self._build_tier3(story)
        ctx.active_storylets = story.active_storylets or []
        ctx.active_consequences = [
            c for c in (story.consequence_log or []) if c.get("is_active")
        ]

        ctx.total_tokens = (
            len(ctx.tier1_identity.split()) +
            len(ctx.tier2_memory.split()) +
            len(ctx.tier3_situational.split())
        ) * 1.3  # rough token estimate

        return ctx

    def _build_tier1(self, story, ocean: dict, pad: dict, active_factors: list) -> str:
        """Build Tier 1: archetype + emotion + personality + active factors."""
        lines = [
            f"[IDENTITY] Client lifecycle: {story.lifecycle_state}",
            f"[IDENTITY] Total calls: {story.total_calls}, Relationship: {story.relationship_score}/100",
        ]
        if ocean:
            lines.append(
                f"[OCEAN] O={ocean.get('O', 0.5):.1f} C={ocean.get('C', 0.5):.1f} "
                f"E={ocean.get('E', 0.5):.1f} A={ocean.get('A', 0.5):.1f} N={ocean.get('N', 0.5):.1f}"
            )
        if pad:
            lines.append(
                f"[PAD] Pleasure={pad.get('pleasure', 0):.1f} "
                f"Arousal={pad.get('arousal', 0):.1f} Dominance={pad.get('dominance', 0):.1f}"
            )
        for f in active_factors[:3]:  # max 3 active
            lines.append(f"[FACTOR:{f['code']}] intensity={f.get('intensity', 0.5):.1f}")
        return "\n".join(lines)

    async def _build_tier2(self, story, db: AsyncSession) -> str:
        """Build Tier 2: past calls summary + consequences + promises."""
        lines = []

        # Episodic memories (key moments from past calls)
        result = await db.execute(
            select(EpisodicMemory)
            .where(EpisodicMemory.client_story_id == story.id)
            .order_by(EpisodicMemory.created_at.desc())
            .limit(10)
        )
        memories = result.scalars().all()
        if memories:
            lines.append("[MEMORY] Key moments from past calls:")
            for m in reversed(memories):
                lines.append(f"  - Call #{m.call_number}: {m.content[:100]}")

        # Active consequences
        for c in (story.consequence_log or []):
            if c.get("is_active"):
                lines.append(f"[CONSEQUENCE:{c.get('level', 'local')}] {c.get('effect_description', '')[:80]}")

        # Promises
        promises = (story.memory or {}).get("promises", [])
        for p in promises[-5:]:  # last 5
            status = "KEPT" if p.get("fulfilled") else "PENDING"
            lines.append(f"[PROMISE:{status}] {p.get('text', '')[:60]}")

        return "\n".join(lines)

    def _build_tier3(self, story) -> str:
        """Build Tier 3: active storylets + between-call events."""
        lines = []
        for s in (story.active_storylets or []):
            tpl = next((t for t in STORYLET_TEMPLATES if t["code"] == s), None)
            if tpl:
                lines.append(f"[STORYLET:{s}] {tpl['narrative'][:100]}")
        return "\n".join(lines)

    # ─── ADVANCE STORY (after each call) ────────────────

    async def advance_story(
        self, result: SessionResult, db: AsyncSession
    ) -> dict:
        """
        Main post-call processing. Called by Agent 1 after session ends.
        1. Updates lifecycle state based on session outcome
        2. Calculates relationship_score delta
        3. Evaluates and activates storylets
        4. Generates between-call events
        Returns summary of changes for Agent 7 (CRM) display.
        """
        story = await self.load_story(result.client_story_id, db)
        if not story:
            logger.error(f"ClientStory {result.client_story_id} not found")
            return {"error": "story_not_found"}

        changes = {"story_id": story.id, "changes": []}

        # 1. Update call count
        story.total_calls = (story.total_calls or 0) + 1

        # 2. Calculate relationship delta
        rel_delta = self._calculate_relationship_delta(result)
        old_rel = story.relationship_score or 50.0
        story.relationship_score = max(0, min(100, old_rel + rel_delta))
        if rel_delta != 0:
            changes["changes"].append(
                f"Relationship: {old_rel:.0f} → {story.relationship_score:.0f} ({rel_delta:+.0f})"
            )

        # 3. Transition lifecycle state
        new_state = self._determine_next_state(story, result)
        if new_state and new_state != story.lifecycle_state:
            old_state = story.lifecycle_state
            story.lifecycle_state = new_state
            changes["changes"].append(f"State: {old_state} → {new_state}")

            # Create status_change event for CRM timeline
            await self._create_game_event(
                story, "status_change", db,
                title=f"Статус: {old_state} → {new_state}",
                content=f"После звонка #{story.total_calls}",
            )

        # 4. Save promises and key moments to memory
        memory = story.memory or {}
        for p in result.promises_made:
            memory.setdefault("promises", []).append({
                "text": p, "call_number": story.total_calls,
                "fulfilled": False, "created_at": datetime.utcnow().isoformat(),
            })
        for km in result.key_moments:
            memory.setdefault("key_moments", []).append({
                "text": km, "call_number": story.total_calls,
                "created_at": datetime.utcnow().isoformat(),
            })
        story.memory = memory

        # 5. Process consequences from stage directions
        for sd in result.stage_directions:
            if sd.get("type") == "consequence":
                consequence = ConsequenceEvent(
                    level=sd.get("level", CONSEQUENCE_LOCAL),
                    trigger_action=sd.get("trigger", ""),
                    effect_description=sd.get("description", ""),
                    source_agent="agent_1",
                )
                await self.apply_consequence(consequence, story, db)

        # 6. Evaluate storylets
        activated = await self._evaluate_storylets(story, result, db)
        for s in activated:
            changes["changes"].append(f"Storylet activated: {s.storylet_code}")

        # 7. Generate between-call events for frontend panel
        events = await self._generate_between_call_events(story, result, db)
        changes["between_call_events"] = len(events)

        await db.flush()
        logger.info(f"Story {story.id} advanced: {changes}")
        return changes

    def _calculate_relationship_delta(self, result: SessionResult) -> float:
        """Compute relationship_score change from session."""
        delta = 0.0
        if result.empathy_detected:
            delta += REL_EMPATHY_DETECTED
        if result.rudeness_detected:
            delta += REL_RUDENESS
        for _ in result.promises_broken:
            delta += REL_PROMISE_BROKEN
        if result.score_total >= 90:
            delta += REL_PERFECT_CALL
        elif result.score_total >= 70:
            delta += REL_PROMISE_KEPT
        if result.legal_errors:
            delta -= len(result.legal_errors) * 2
        return delta

    def _determine_next_state(self, story, result: SessionResult) -> Optional[str]:
        """Determine lifecycle state transition based on session outcome."""
        current = story.lifecycle_state
        allowed = LIFECYCLE_TRANSITIONS.get(current, [])
        if not allowed:
            return None  # terminal state

        emotion = result.final_emotion_state
        score = result.score_total

        # Emotion-gated transitions
        if emotion in ("hostile", "hangup"):
            if "REJECTED" in allowed:
                return "REJECTED"
        if emotion == "deal" and score >= 70:
            if "MEETING_SET" in allowed:
                return "MEETING_SET"
            if "DEAL_CLOSED" in allowed:
                return "DEAL_CLOSED"
        if emotion in ("curious", "considering", "negotiating"):
            if "INTERESTED" in allowed:
                return "INTERESTED"
        if emotion == "callback":
            if "CALLBACK_SCHEDULED" in allowed:
                return "CALLBACK_SCHEDULED"

        # Score-gated fallbacks
        if score >= 50 and "INTERESTED" in allowed:
            return "INTERESTED"
        if score < 30 and "REJECTED" in allowed:
            return "REJECTED"

        # Default: stay in current state if follow-up
        if current == "CALLBACK_SCHEDULED" and "FOLLOW_UP_CALL" in allowed:
            return "FOLLOW_UP_CALL"

        return None  # no transition

    # ─── CONSEQUENCES ───────────────────────────────────

    async def apply_consequence(
        self, consequence: ConsequenceEvent, story: ClientStory, db: AsyncSession
    ) -> None:
        """Apply a consequence event to a ClientStory. Called by Agent 3 (traps) and Agent 1."""
        log = story.consequence_log or []

        # Enforce limits: max 3 local, 5 global
        active_local = sum(1 for c in log if c.get("level") == CONSEQUENCE_LOCAL and c.get("is_active"))
        active_global = sum(1 for c in log if c.get("level") == CONSEQUENCE_GLOBAL and c.get("is_active"))

        if consequence.level == CONSEQUENCE_LOCAL and active_local >= 3:
            # Expire oldest local
            for c in log:
                if c.get("level") == CONSEQUENCE_LOCAL and c.get("is_active"):
                    c["is_active"] = False
                    break

        if consequence.level == CONSEQUENCE_GLOBAL and active_global >= 5:
            for c in log:
                if c.get("level") == CONSEQUENCE_GLOBAL and c.get("is_active"):
                    c["is_active"] = False
                    break

        log.append({
            "id": consequence.id,
            "level": consequence.level,
            "trigger_action": consequence.trigger_action,
            "effect_description": consequence.effect_description,
            "applied_at": consequence.applied_at.isoformat(),
            "expires_at": consequence.expires_at.isoformat() if consequence.expires_at else None,
            "is_active": True,
            "source_agent": consequence.source_agent,
        })
        story.consequence_log = log

        # If global consequence, create event for CRM
        if consequence.level == CONSEQUENCE_GLOBAL:
            await self._create_game_event(
                story, "consequence", db,
                title=f"Глобальное последствие",
                content=consequence.effect_description,
            )

    # ─── STORYLETS ──────────────────────────────────────

    async def _evaluate_storylets(
        self, story: ClientStory, result: SessionResult, db: AsyncSession
    ) -> list[StoryletActivation]:
        """Check preconditions and activate matching storylets. Max 2 per call."""
        activated = []
        already_active = set(story.active_storylets or [])

        # Sort by priority (highest first)
        candidates = sorted(STORYLET_TEMPLATES, key=lambda t: t["priority"], reverse=True)

        for tpl in candidates:
            if len(activated) >= 2:
                break
            if tpl["code"] in already_active:
                continue
            if self._check_storylet_preconditions(tpl, story, result):
                activation = StoryletActivation(
                    storylet_code=tpl["code"],
                    narrative_text=tpl["narrative"],
                    effects=tpl["effects"],
                    priority=tpl["priority"],
                )
                activated.append(activation)
                already_active.add(tpl["code"])

                # Apply effects
                effects = tpl["effects"]
                if "force_state" in effects:
                    story.lifecycle_state = effects["force_state"]
                if "relationship_delta" in effects:
                    story.relationship_score = max(0, min(100,
                        (story.relationship_score or 50) + effects["relationship_delta"]
                    ))

                # Create storylet event for CRM
                await self._create_game_event(
                    story, "storylet", db,
                    title=tpl["code"].replace("_", " ").title(),
                    content=tpl["narrative"],
                )

        story.active_storylets = list(already_active)
        return activated

    def _check_storylet_preconditions(self, tpl: dict, story: ClientStory, result: SessionResult) -> bool:
        """Check if a storylet's preconditions are met."""
        pre = tpl["preconditions"]

        if "lifecycle_state" in pre and story.lifecycle_state != pre["lifecycle_state"]:
            return False
        if "min_calls" in pre and (story.total_calls or 0) < pre["min_calls"]:
            return False
        if "min_debt" in pre:
            debt = (story.memory or {}).get("debt_amount", 0)
            if debt < pre["min_debt"]:
                return False
        if "max_debt" in pre:
            debt = (story.memory or {}).get("debt_amount", 0)
            if debt > pre["max_debt"]:
                return False
        if "min_difficulty" in pre:
            if (story.difficulty or 5) < pre["min_difficulty"]:
                return False
        if "family_status" in pre:
            family = (story.personality_profile or {}).get("family_status", "")
            if family != pre["family_status"]:
                return False

        return True

    # ─── BETWEEN-CALL EVENTS ────────────────────────────

    async def _generate_between_call_events(
        self, story: ClientStory, result: SessionResult, db: AsyncSession
    ) -> list[BetweenCallEvent]:
        """Generate events for frontend panel between calls. NOT SMS — panel only."""
        events = []
        state = story.lifecycle_state

        # Client messages based on state
        if state in ("THINKING", "CALLBACK_SCHEDULED"):
            import random
            if random.random() < 0.6:  # 60% chance
                messages = [
                    "Я поговорил с женой, она беспокоится. Можете ещё раз объяснить про квартиру?",
                    "Спасибо за информацию. Я думаю.",
                    "А если я просто не буду платить, что будет?",
                    "Мне друг сказал что банкротство это позор. Это правда?",
                    "Сколько точно будет стоить вся процедура?",
                ]
                msg = random.choice(messages)
                event = BetweenCallEvent(
                    event_type="message",
                    title="Сообщение от клиента",
                    content=msg,
                )
                events.append(event)
                await self._create_game_event(
                    story, "message", db, title="Сообщение от клиента", content=msg,
                )

        # Consequence notifications
        for c in (story.consequence_log or []):
            if c.get("is_active") and c.get("level") != CONSEQUENCE_COSMETIC:
                event = BetweenCallEvent(
                    event_type="consequence",
                    title="Последствие",
                    content=c.get("effect_description", ""),
                )
                events.append(event)

        return events

    # ─── HELPER: Create GameClientEvent for CRM ─────────

    async def _create_game_event(
        self, story: ClientStory, event_type: str, db: AsyncSession,
        title: str = "", content: str = "", payload: dict = None,
    ) -> None:
        """Create a GameClientEvent for the CRM timeline (Agent 7)."""
        event = GameClientEvent(
            id=str(uuid.uuid4()),
            client_story_id=story.id,
            user_id=story.user_id,
            event_type=event_type,
            title=title,
            narrative_content=content,
            game_timestamp=datetime.utcnow(),
            metadata_=payload or {},
        )
        db.add(event)

    # ─── CONVERGENCE ────────────────────────────────────

    async def check_convergence(self, story: ClientStory, db: AsyncSession) -> bool:
        """
        Check if narrative needs bottleneck convergence.
        Triggers: every 3rd call, or relationship_score change > 20, or high-priority storylet.
        """
        if (story.total_calls or 0) % 3 == 0 and (story.total_calls or 0) > 0:
            return True
        # Check for dramatic weight threshold
        active_consequences = sum(
            1 for c in (story.consequence_log or []) if c.get("is_active")
        )
        storylet_priority_sum = sum(
            next((t["priority"] for t in STORYLET_TEMPLATES if t["code"] == s), 0)
            for s in (story.active_storylets or [])
        )
        dramatic_weight = active_consequences * 2 + storylet_priority_sum
        return dramatic_weight > 15

    # ─── PUBLIC API for other agents ────────────────────

    async def get_pending_events(self, story_id: str, db: AsyncSession) -> list[dict]:
        """Get pending between-call events for Agent 7 (CRM) display."""
        result = await db.execute(
            select(GameClientEvent)
            .where(GameClientEvent.client_story_id == story_id)
            .where(GameClientEvent.is_read == False)
            .order_by(GameClientEvent.game_timestamp.desc())
            .limit(20)
        )
        events = result.scalars().all()
        return [
            {
                "id": str(e.id),
                "type": e.event_type,
                "title": e.title,
                "content": e.narrative_content,
                "timestamp": e.game_timestamp.isoformat() if e.game_timestamp else "",
                "payload": e.metadata_ or {},
            }
            for e in events
        ]

    async def get_active_factors(self, story_id: str, db: AsyncSession) -> list[dict]:
        """Get active human factors for Agent 3 (traps) and Agent 4 (voice)."""
        story = await self.load_story(story_id, db)
        if not story:
            return []
        profile = story.personality_profile or {}
        factors = profile.get("human_factors", [])
        return [f for f in factors if f.get("active", False)]

    async def get_relationship_score(self, story_id: str, db: AsyncSession) -> float:
        """Get current relationship score for Agent 5 (gamification)."""
        story = await self.load_story(story_id, db)
        return story.relationship_score if story else 50.0


# ═══════════════════════════════════════════════════════════
# SINGLETON INSTANCE
# ═══════════════════════════════════════════════════════════

game_director = GameDirectorEngine()
