"""
Game Director Engine — Central Orchestrator for Hunter888 v5.

This is the BRAIN of the entire narrative game system.
It connects all 8 agents into a unified story flow:

  Agent 1 (Roleplay) ←→ Game Director ←→ Agent 3 (Traps)
  Agent 2 (Scoring)  ←→ Game Director ←→ Agent 4 (Voice)
  Agent 5 (Gamification) ←→ Game Director ←→ Agent 6 (Generator)
  Agent 7 (CRM)      ←→ Game Director ←→ Agent 8 (PvP)

Data flow:
  1. Manager starts session → GD loads ClientStory from DB
  2. GD builds context injection (3-tier) → injected into LLM prompt
  3. During session: stage directions analyzed for consequences
  4. After session: GD advances story, evaluates storylets, generates events
  5. Between calls: GD generates frontend panel events

All inter-agent communication flows through this module.
Agents do NOT import each other — they import game_director.
"""

import asyncio
import logging
import uuid
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from dataclasses import dataclass, field
from typing import Optional

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.roleplay import (
    ClientStory,
    PersonalityProfile,
    EpisodicMemory,
)
from app.models.game_crm import GameClientEvent, GameEventType
from app.models.training import TrainingSession

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════
# DATA CONTRACTS (used by all agents)
# ═══════════════════════════════════════════════════════════

# Lifecycle states for the narrative state machine (between calls)
LIFECYCLE_STATES = [
    "NEW_LEAD", "FIRST_CONTACT", "INTERESTED", "OBJECTING",
    "THINKING", "CALLBACK_SCHEDULED", "FOLLOW_UP_CALL",
    "MEETING_SET", "DEAL_CLOSED", "REJECTED", "GHOSTING",
    "NO_ANSWER", "REACTIVATION",
]

# Allowed transitions: {from_state: [to_states]}
LIFECYCLE_TRANSITIONS = {
    "NEW_LEAD": ["FIRST_CONTACT"],
    "FIRST_CONTACT": ["INTERESTED", "REJECTED", "CALLBACK_SCHEDULED", "NO_ANSWER"],
    "INTERESTED": ["MEETING_SET", "THINKING", "OBJECTING"],
    "OBJECTING": ["INTERESTED", "REJECTED", "CALLBACK_SCHEDULED"],
    "THINKING": ["CALLBACK_SCHEDULED", "GHOSTING", "INTERESTED"],
    "CALLBACK_SCHEDULED": ["FOLLOW_UP_CALL", "NO_ANSWER", "GHOSTING"],
    "FOLLOW_UP_CALL": ["MEETING_SET", "OBJECTING", "REJECTED"],
    "MEETING_SET": ["DEAL_CLOSED", "REJECTED", "NO_ANSWER"],
    "DEAL_CLOSED": [],  # terminal
    "REJECTED": ["REACTIVATION"],
    "GHOSTING": ["REACTIVATION"],
    "NO_ANSWER": ["FIRST_CONTACT", "GHOSTING"],
    "REACTIVATION": ["INTERESTED", "REJECTED"],
}

# Consequence levels
CONSEQUENCE_COSMETIC = "cosmetic"
CONSEQUENCE_LOCAL = "local"
CONSEQUENCE_GLOBAL = "global"

# Relationship score modifiers
REL_PROMISE_KEPT = 5
REL_EMPATHY_DETECTED = 3
REL_PROMISE_BROKEN = -10
REL_RUDENESS = -15
REL_FORGOT_CLIENT = -5
REL_PERFECT_CALL = 10


@dataclass
class ConsequenceEvent:
    """Consequence generated by agent actions, processed by Game Director."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    level: str = CONSEQUENCE_LOCAL  # cosmetic | local | global
    trigger_action: str = ""
    effect_description: str = ""
    applied_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: Optional[datetime] = None
    is_active: bool = True
    source_agent: str = ""  # "agent_1", "agent_3", etc.


@dataclass
class StoryletActivation:
    """A storylet that has been activated for a client."""
    storylet_code: str = ""
    narrative_text: str = ""
    effects: dict = field(default_factory=dict)
    priority: int = 5
    activated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class BetweenCallEvent:
    """Event generated between calls for the frontend panel."""
    event_type: str = "message"  # message | status_change | consequence | storylet | callback
    title: str = ""
    content: str = ""
    game_timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    payload: dict = field(default_factory=dict)


@dataclass
class ContextInjection:
    """Three-tier context assembled for LLM prompt injection."""
    tier1_identity: str = ""    # archetype + emotion + personality + factors (~500 tokens)
    tier2_memory: str = ""      # past calls + consequences + promises (~800 tokens)
    tier3_situational: str = "" # storylets + events + reputation (~400 tokens)
    total_tokens: int = 0
    active_factors: list = field(default_factory=list)
    active_storylets: list = field(default_factory=list)
    active_consequences: list = field(default_factory=list)


@dataclass
class SessionResult:
    """Result of a completed training session, sent by Agent 1."""
    session_id: str = ""
    client_story_id: str = ""
    final_emotion_state: str = "cold"
    score_total: float = 0.0
    score_breakdown: dict = field(default_factory=dict)
    traps_fell: list = field(default_factory=list)
    traps_dodged: list = field(default_factory=list)
    promises_made: list = field(default_factory=list)
    promises_broken: list = field(default_factory=list)
    key_moments: list = field(default_factory=list)
    stage_directions: list = field(default_factory=list)
    duration_seconds: int = 0
    empathy_detected: bool = False
    rudeness_detected: bool = False
    legal_errors: list = field(default_factory=list)


# ═══════════════════════════════════════════════════════════
# STORYLET TEMPLATES (BFL Domain)
# ═══════════════════════════════════════════════════════════

STORYLET_TEMPLATES = [
    {
        "code": "wife_found_out",
        "preconditions": {"lifecycle_state": "THINKING", "min_days_in_state": 3, "family_status": "married", "min_debt": 300_000},
        "narrative": "Жена клиента узнала о долгах. Она в ярости и напугана. Клиент под двойным давлением — от кредиторов и от семьи.",
        "effects": {"activate_factors": ["anxiety", "social_fear"], "arousal_delta": 0.5},
        "priority": 8,
        "cooldown_days": 30,
    },
    {
        "code": "collectors_arrived",
        "preconditions": {"lifecycle_state": "GHOSTING", "min_days_in_state": 7, "min_debt": 500_000},
        "narrative": "Коллекторы пришли домой к клиенту. Клиент в панике и готов разговаривать, но доверие на нуле.",
        "effects": {"force_state": "REACTIVATION", "pleasure_delta": -0.8, "arousal_delta": 0.9, "activate_factors": ["distrust"]},
        "priority": 9,
        "cooldown_days": 60,
    },
    {
        "code": "friend_recommended_lawyer",
        "preconditions": {"min_calls": 2, "manager_never_mentioned_bankruptcy": True},
        "narrative": "Друг клиента порекомендовал конкурирующего юриста. Клиент теперь имеет альтернативу.",
        "effects": {"activate_factors": ["competitiveness"], "add_objection_chain": "competitor_comparison"},
        "priority": 6,
        "cooldown_days": 20,
    },
    {
        "code": "court_order_received",
        "preconditions": {"lifecycle_state": "REJECTED", "min_days_in_state": 30, "min_debt": 2_000_000},
        "narrative": "Клиент получил судебный приказ. Ситуация стала срочной.",
        "effects": {"force_state": "REACTIVATION", "activate_factors": ["anger", "anxiety"], "urgency": True},
        "priority": 10,
        "cooldown_days": 90,
    },
    {
        "code": "salary_garnishment",
        "preconditions": {"lifecycle_state": "GHOSTING", "min_days_in_state": 14, "min_debt": 500_000},
        "narrative": "С зарплаты клиента удерживают 50%. Финансовое отчаяние достигло пика.",
        "effects": {"force_state": "INTERESTED", "pleasure_delta": -1.0, "dominance_delta": -0.8},
        "priority": 9,
        "cooldown_days": 60,
    },
    {
        "code": "positive_precedent",
        "preconditions": {"lifecycle_state": "THINKING", "manager_cited_law_articles": True},
        "narrative": "Клиент прочитал про успешное дело о банкротстве в интернете. Надежда выросла.",
        "effects": {"relationship_delta": 10, "activate_factors": ["curiosity", "optimism"]},
        "priority": 5,
        "cooldown_days": 15,
    },
    {
        "code": "job_loss",
        "preconditions": {"min_difficulty": 7, "lifecycle_state": "THINKING", "min_days_in_state": 5},
        "narrative": "Клиент потерял работу. Финансовая ситуация резко ухудшилась.",
        "effects": {"activate_factors": ["anxiety", "pessimism"], "debt_pressure_delta": 0.3},
        "priority": 7,
        "cooldown_days": 30,
    },
    {
        "code": "bank_restructuring_offer",
        "preconditions": {"lifecycle_state": "OBJECTING", "min_calls": 3, "max_debt": 1_000_000},
        "narrative": "Банк предложил реструктуризацию. Клиент рассматривает альтернативу банкротству.",
        "effects": {"activate_factors": ["competitiveness"], "add_objection_chain": "bank_alternative"},
        "priority": 6,
        "cooldown_days": 20,
    },
    # ── Wave 1 iteration: 5 new storylets ──────────────────
    {
        "code": "debt_penalty_increase",
        "preconditions": {"lifecycle_state": "THINKING", "min_days_in_state": 7, "min_debt": 200_000},
        "narrative": "Пени и штрафы увеличили долг клиента на 15%. Время работает против него.",
        "effects": {"arousal_delta": 0.3, "activate_factors": ["anxiety", "urgency"]},
        "priority": 5,
        "cooldown_days": 14,
    },
    {
        "code": "manager_empathy_detected",
        "preconditions": {"lifecycle_state": "INTERESTED", "min_calls": 2, "min_avg_score": 70},
        "narrative": "Клиент почувствовал искреннее участие менеджера. Доверие укрепляется.",
        "effects": {"relationship_delta": 15, "pleasure_delta": 0.3, "activate_factors": ["trust"]},
        "priority": 4,
        "cooldown_days": 10,
    },
    {
        "code": "competing_firm_call",
        "preconditions": {"lifecycle_state": "CALLBACK_SCHEDULED", "min_days_in_state": 2},
        "narrative": "Клиенту позвонили из другой юридической фирмы. Он сравнивает предложения.",
        "effects": {"activate_factors": ["competitiveness", "doubt"], "relationship_delta": -5},
        "priority": 7,
        "cooldown_days": 15,
    },
    {
        "code": "family_support_emerges",
        "preconditions": {"lifecycle_state": "THINKING", "family_status": "married", "min_calls": 3},
        "narrative": "Супруг(а) клиента поддержал(а) идею банкротства. Семейное давление снизилось.",
        "effects": {"relationship_delta": 10, "pleasure_delta": 0.4, "activate_factors": ["relief", "optimism"]},
        "priority": 5,
        "cooldown_days": 30,
    },
    {
        "code": "isolation_deepens",
        "preconditions": {"lifecycle_state": "GHOSTING", "min_days_in_state": 10},
        "narrative": "Клиент всё больше замыкается в себе. Долги давят, но просить помощь стыдно.",
        "effects": {"pleasure_delta": -0.5, "dominance_delta": -0.3, "activate_factors": ["shame", "isolation"]},
        "priority": 6,
        "cooldown_days": 20,
    },
]


# ═══════════════════════════════════════════════════════════
# CORE ENGINE
# ═══════════════════════════════════════════════════════════

class GameDirectorEngine:
    """
    Central orchestrator. All inter-agent data flows through here.

    Usage by agents:
        from app.services.game_director import game_director
        # Agent 1: get context for LLM prompt
        ctx = await game_director.build_context_injection(story_id, db)
        # Agent 1: report session result
        await game_director.advance_story(session_result, db)
        # Agent 3: report trap consequence
        await game_director.apply_consequence(consequence, db)
        # Agent 7: get pending events
        events = await game_director.get_pending_events(story_id, db)
    """

    def __init__(self) -> None:
        # Per-story asyncio locks to prevent concurrent advance_story calls
        # on the same story (TOCTOU fix for storylet cooldown & state mutations).
        # defaultdict creates a new Lock per story_id on first access.
        self._story_locks: dict[str, asyncio.Lock] = defaultdict(asyncio.Lock)

    def _get_story_lock(self, story_id: str) -> asyncio.Lock:
        """Get or create an asyncio.Lock for the given story_id."""
        return self._story_locks[story_id]

    # ─── STORY LIFECYCLE ────────────────────────────────

    async def create_story(
        self,
        user_id: str,
        scenario_code: str,
        personality_profile: dict,
        difficulty: int,
        db: AsyncSession,
    ) -> ClientStory:
        """Create a new ClientStory. Called when manager starts a multi-call arc."""
        # Resolve VRM avatar model from personality profile archetype
        from app.services.avatar_assignment import resolve_model_key
        archetype_code = personality_profile.get("archetype_code") if personality_profile else None
        vrm_model_id = resolve_model_key(archetype_code)

        story = ClientStory(
            id=str(uuid.uuid4()),
            user_id=user_id,
            lifecycle_state="NEW_LEAD",
            total_calls=0,
            relationship_score=50.0,
            personality_profile=personality_profile,
            vrm_model_id=vrm_model_id,
            memory={"promises": [], "key_moments": [], "insults": [], "agreements": []},
            active_storylets=[],
            consequence_log=[],
            difficulty=difficulty,
            scenario_code=scenario_code,
        )
        db.add(story)
        await db.flush()
        logger.info(f"Created ClientStory {story.id} for user {user_id}")
        return story

    async def load_story(self, story_id: str, db: AsyncSession) -> Optional[ClientStory]:
        """Load a ClientStory from DB. Cached in Redis for 24h by caller."""
        result = await db.execute(select(ClientStory).where(ClientStory.id == story_id))
        return result.scalar_one_or_none()

    # ─── CONTEXT INJECTION (for Agent 1 / LLM) ─────────

    async def build_context_injection(
        self, story_id: str, db: AsyncSession
    ) -> ContextInjection:
        """
        Assemble 3-tier context from memory, consequences, storylets.
        Called by Agent 1 before each call via build_multi_call_prompt().
        Token budget: ~1700 total (500 + 800 + 400).
        """
        story = await self.load_story(story_id, db)
        if not story:
            return ContextInjection()

        ctx = ContextInjection()

        # Tier 1: Identity Core (always injected, ~500 tokens)
        profile = story.personality_profile or {}
        ocean = profile.get("ocean", {})
        pad = profile.get("pad", {})
        factors = profile.get("human_factors", [])
        active_factors = [f for f in factors if f.get("active", False)]

        ctx.tier1_identity = self._build_tier1(story, ocean, pad, active_factors)
        ctx.active_factors = active_factors

        # Tier 2: Story Memory (if calls > 1, ~800 tokens)
        if story.total_calls > 0:
            ctx.tier2_memory = await self._build_tier2(story, db)

        # Tier 3: Situational (storylets + events, ~400 tokens)
        ctx.tier3_situational = self._build_tier3(story)
        ctx.active_storylets = story.active_storylets or []
        ctx.active_consequences = [
            c for c in (story.consequence_log or []) if c.get("is_active")
        ]

        ctx.total_tokens = (
            len(ctx.tier1_identity.split()) +
            len(ctx.tier2_memory.split()) +
            len(ctx.tier3_situational.split())
        ) * 1.3  # rough token estimate

        return ctx

    def _build_tier1(self, story, ocean: dict, pad: dict, active_factors: list) -> str:
        """Build Tier 1: archetype + emotion + personality + active factors."""
        lines = [
            f"[IDENTITY] Client lifecycle: {story.lifecycle_state}",
            f"[IDENTITY] Total calls: {story.total_calls}, Relationship: {story.relationship_score}/100",
        ]
        if ocean:
            lines.append(
                f"[OCEAN] O={ocean.get('O', 0.5):.1f} C={ocean.get('C', 0.5):.1f} "
                f"E={ocean.get('E', 0.5):.1f} A={ocean.get('A', 0.5):.1f} N={ocean.get('N', 0.5):.1f}"
            )
        if pad:
            lines.append(
                f"[PAD] Pleasure={pad.get('pleasure', 0):.1f} "
                f"Arousal={pad.get('arousal', 0):.1f} Dominance={pad.get('dominance', 0):.1f}"
            )
        for f in active_factors[:3]:  # max 3 active
            lines.append(f"[FACTOR:{f['code']}] intensity={f.get('intensity', 0.5):.1f}")

        # Inject behavioral modifiers from personality profile (Wave 1.2)
        from app.services.llm import format_personality_for_prompt
        profile = story.personality_profile or {}
        modifier_text = format_personality_for_prompt(profile)
        if modifier_text:
            lines.append(modifier_text)

        return "\n".join(lines)

    async def _build_tier2(self, story, db: AsyncSession) -> str:
        """Build Tier 2: past calls summary + consequences + promises."""
        lines = []

        # Episodic memories (key moments from past calls)
        result = await db.execute(
            select(EpisodicMemory)
            .where(EpisodicMemory.story_id == story.id)
            .order_by(EpisodicMemory.created_at.desc())
            .limit(10)
        )
        memories = result.scalars().all()
        if memories:
            lines.append("[MEMORY] Key moments from past calls:")
            for m in reversed(memories):
                lines.append(f"  - Call #{m.call_number}: {m.content[:100]}")

        # Active consequences
        for c in (story.consequence_log or []):
            if c.get("is_active"):
                lines.append(f"[CONSEQUENCE:{c.get('level', 'local')}] {c.get('effect_description', '')[:80]}")

        # Promises
        promises = (story.memory or {}).get("promises", [])
        for p in promises[-5:]:  # last 5
            status = "KEPT" if p.get("fulfilled") else "PENDING"
            lines.append(f"[PROMISE:{status}] {p.get('text', '')[:60]}")

        return "\n".join(lines)

    def _build_tier3(self, story) -> str:
        """Build Tier 3: active storylets + between-call events."""
        lines = []
        for s in (story.active_storylets or []):
            tpl = next((t for t in STORYLET_TEMPLATES if t["code"] == s), None)
            if tpl:
                lines.append(f"[STORYLET:{s}] {tpl['narrative'][:100]}")
        return "\n".join(lines)

    # ─── ADVANCE STORY (after each call) ────────────────

    async def advance_story(
        self, result: SessionResult, db: AsyncSession
    ) -> dict:
        """
        Main post-call processing. Called by Agent 1 after session ends.
        1. Updates lifecycle state based on session outcome
        2. Calculates relationship_score delta
        3. Evaluates and activates storylets
        4. Generates between-call events
        Returns summary of changes for Agent 7 (CRM) display.

        Uses per-story asyncio lock to prevent TOCTOU races on concurrent calls
        (e.g., two training sessions finishing simultaneously for the same story).
        """
        # Per-story lock prevents concurrent advance_story calls from racing
        # on storylet cooldowns, relationship_score, lifecycle_state, etc.
        # IMPORTANT: load_story MUST be inside the lock so that a queued
        # coroutine loads fresh data after the previous one has flushed.
        async with self._get_story_lock(str(result.client_story_id)):
            story = await self.load_story(result.client_story_id, db)
            if not story:
                logger.error(f"ClientStory {result.client_story_id} not found")
                raise ValueError(f"ClientStory {result.client_story_id} not found")

            changes = {"story_id": story.id, "changes": []}

            # 1. Update call count
            story.total_calls = (story.total_calls or 0) + 1

            # 2. Calculate relationship delta
            rel_delta = self._calculate_relationship_delta(result)
            old_rel = story.relationship_score or 50.0
            story.relationship_score = max(0, min(100, old_rel + rel_delta))
            if rel_delta != 0:
                changes["changes"].append(
                    f"Relationship: {old_rel:.0f} → {story.relationship_score:.0f} ({rel_delta:+.0f})"
                )

            # 3. Transition lifecycle state
            new_state = self._determine_next_state(story, result)
            if new_state and new_state != story.lifecycle_state:
                old_state = story.lifecycle_state
                story.lifecycle_state = new_state
                changes["changes"].append(f"State: {old_state} → {new_state}")

                # Record state entry timestamp for time-based gates (Task 1.2)
                director = story.director_state or {}
                director["state_entered_at"] = datetime.now(timezone.utc).isoformat()
                director["previous_state"] = old_state
                story.director_state = director

                # Create status_change event for CRM timeline
                await self._create_game_event(
                    story, "status_change", db,
                    title=f"Статус: {old_state} → {new_state}",
                    content=f"После звонка #{story.total_calls}",
                )

                # TZ-1 §11.2: mirror story lifecycle into canonical DomainEvent
                # when the story is linked to a real CRM client.
                try:
                    from app.services.client_story_projector import record_story_lifecycle_change

                    await record_story_lifecycle_change(
                        db,
                        story=story,
                        old_state=old_state,
                        new_state=new_state,
                        actor_id=story.user_id,
                        source="game_director",
                        extra={"call_number": story.total_calls},
                    )
                except Exception:
                    import logging as _logging
                    _logging.getLogger(__name__).warning(
                        "advance_story: domain mirror of lifecycle change failed", exc_info=True
                    )

            # 4. Save promises and key moments to memory
            memory = story.memory or {}
            for p in result.promises_made:
                memory.setdefault("promises", []).append({
                    "text": p, "call_number": story.total_calls,
                    "fulfilled": False, "created_at": datetime.now(timezone.utc).isoformat(),
                })
            for km in result.key_moments:
                memory.setdefault("key_moments", []).append({
                    "text": km, "call_number": story.total_calls,
                    "created_at": datetime.now(timezone.utc).isoformat(),
                })
            story.memory = memory

            # 5. Process consequences from stage directions
            for sd in result.stage_directions:
                if sd.get("type") == "consequence":
                    consequence = ConsequenceEvent(
                        level=sd.get("level", CONSEQUENCE_LOCAL),
                        trigger_action=sd.get("trigger", ""),
                        effect_description=sd.get("description", ""),
                        source_agent="agent_1",
                    )
                    await self.apply_consequence(consequence, story, db)

            # 6. Evaluate storylets
            activated = await self._evaluate_storylets(story, result, db)
            for s in activated:
                changes["changes"].append(f"Storylet activated: {s.storylet_code}")

            # 7. Generate between-call events for frontend panel
            events = await self._generate_between_call_events(story, result, db)
            changes["between_call_events"] = len(events)

            await db.flush()
            logger.info(f"Story {story.id} advanced: {changes}")
            return changes

    def _calculate_relationship_delta(self, result: SessionResult) -> float:
        """Compute relationship_score change from session."""
        delta = 0.0
        if result.empathy_detected:
            delta += REL_EMPATHY_DETECTED
        if result.rudeness_detected:
            delta += REL_RUDENESS
        for _ in result.promises_broken:
            delta += REL_PROMISE_BROKEN
        if result.score_total >= 90:
            delta += REL_PERFECT_CALL
        elif result.score_total >= 70:
            delta += REL_PROMISE_KEPT
        if result.legal_errors:
            delta -= len(result.legal_errors) * 2
        return delta

    def _determine_next_state(self, story, result: SessionResult) -> Optional[str]:
        """Determine lifecycle state transition based on multi-factor gates.

        Gate hierarchy (Wave 1, Task 1.2):
        1. Emotion gates (primary signal from AI client)
        2. Relationship score gates (prevents unrealistic jumps)
        3. Minimum call count gates (ensures narrative progression)
        4. Time-based gates (prevents rushing through states)
        5. Score fallbacks (catch-all for ambiguous emotions)
        """
        current = story.lifecycle_state
        allowed = LIFECYCLE_TRANSITIONS.get(current, [])
        if not allowed:
            return None  # terminal state

        emotion = result.final_emotion_state
        score = result.score_total
        rel_score = story.relationship_score or 50.0
        total_calls = story.total_calls or 0

        # ── Helper: check time-based gate ──
        def _min_time_in_state_ok(min_hours: int = 0) -> bool:
            """Check if enough time has passed since entering current state."""
            if min_hours <= 0:
                return True
            director = story.director_state or {}
            state_entered_at = director.get("state_entered_at")
            if not state_entered_at:
                return True  # No timestamp recorded — allow transition
            try:
                entered = datetime.fromisoformat(state_entered_at)
                return datetime.now(timezone.utc) - entered >= timedelta(hours=min_hours)
            except (ValueError, TypeError):
                return True

        # ── Negative gates: rejection/hangup (always allowed) ──
        if emotion in ("hostile", "hangup"):
            if "REJECTED" in allowed:
                return "REJECTED"

        # ── DEAL_CLOSED: strictest gate ──
        # Requires: emotion=deal, score>=70, relationship>=60, min 3 calls total
        if emotion == "deal" and score >= 70:
            if "DEAL_CLOSED" in allowed and rel_score >= 60 and total_calls >= 3:
                return "DEAL_CLOSED"
            # If not ready for DEAL_CLOSED, try MEETING_SET instead
            if "MEETING_SET" in allowed and rel_score >= 50 and total_calls >= 2:
                return "MEETING_SET"

        # ── MEETING_SET: requires relationship >= 50, min 2 calls ──
        if emotion == "deal" and score >= 60:
            if "MEETING_SET" in allowed and rel_score >= 50 and total_calls >= 2:
                return "MEETING_SET"

        # ── INTERESTED: requires min 1 call from FIRST_CONTACT ──
        if emotion in ("curious", "considering", "negotiating"):
            if "INTERESTED" in allowed:
                # From FIRST_CONTACT: need at least 1 completed call
                if current == "FIRST_CONTACT" and total_calls < 1:
                    pass  # Stay in FIRST_CONTACT
                else:
                    return "INTERESTED"

        # ── CALLBACK_SCHEDULED: always available if emotion matches ──
        if emotion == "callback":
            if "CALLBACK_SCHEDULED" in allowed:
                return "CALLBACK_SCHEDULED"

        # ── Score-gated fallbacks ──
        if score >= 50 and "INTERESTED" in allowed:
            if current != "FIRST_CONTACT" or total_calls >= 1:
                return "INTERESTED"
        # Mid-range score (30-50): client is unsure, goes to THINKING
        if 30 <= score < 50 and "THINKING" in allowed:
            return "THINKING"
        if score < 30 and "REJECTED" in allowed:
            return "REJECTED"

        # ── Default: advance from CALLBACK_SCHEDULED to FOLLOW_UP ──
        if current == "CALLBACK_SCHEDULED" and "FOLLOW_UP_CALL" in allowed:
            return "FOLLOW_UP_CALL"

        return None  # no transition

    # ─── CONSEQUENCES ───────────────────────────────────

    async def apply_consequence(
        self, consequence: ConsequenceEvent, story: ClientStory, db: AsyncSession
    ) -> None:
        """Apply a consequence event to a ClientStory. Called by Agent 3 (traps) and Agent 1."""
        log = story.consequence_log or []

        # Enforce limits: max 3 local, 5 global
        active_local = sum(1 for c in log if c.get("level") == CONSEQUENCE_LOCAL and c.get("is_active"))
        active_global = sum(1 for c in log if c.get("level") == CONSEQUENCE_GLOBAL and c.get("is_active"))

        if consequence.level == CONSEQUENCE_LOCAL and active_local >= 3:
            # Expire oldest local
            for c in log:
                if c.get("level") == CONSEQUENCE_LOCAL and c.get("is_active"):
                    c["is_active"] = False
                    break

        if consequence.level == CONSEQUENCE_GLOBAL and active_global >= 5:
            for c in log:
                if c.get("level") == CONSEQUENCE_GLOBAL and c.get("is_active"):
                    c["is_active"] = False
                    break

        log.append({
            "id": consequence.id,
            "level": consequence.level,
            "trigger_action": consequence.trigger_action,
            "effect_description": consequence.effect_description,
            "applied_at": consequence.applied_at.isoformat(),
            "expires_at": consequence.expires_at.isoformat() if consequence.expires_at else None,
            "is_active": True,
            "source_agent": consequence.source_agent,
        })
        story.consequence_log = log

        # If global consequence, create event for CRM
        if consequence.level == CONSEQUENCE_GLOBAL:
            await self._create_game_event(
                story, "consequence", db,
                title=f"Глобальное последствие",
                content=consequence.effect_description,
            )

    # ─── STORYLETS ──────────────────────────────────────

    async def _evaluate_storylets(
        self, story: ClientStory, result: SessionResult, db: AsyncSession
    ) -> list[StoryletActivation]:
        """Check preconditions and activate matching storylets. Max 2 per call."""
        activated = []
        already_active = set(story.active_storylets or [])

        # Sort by priority (highest first)
        candidates = sorted(STORYLET_TEMPLATES, key=lambda t: t["priority"], reverse=True)

        for tpl in candidates:
            if len(activated) >= 2:
                break
            if tpl["code"] in already_active:
                continue
            if self._check_storylet_preconditions(tpl, story, result):
                # Capture pre-effect values so we can revert on failure
                _prev_lifecycle = story.lifecycle_state
                _prev_rel_score = story.relationship_score

                # Apply effects to the in-memory story object
                effects = tpl["effects"]
                if "force_state" in effects:
                    story.lifecycle_state = effects["force_state"]
                if "relationship_delta" in effects:
                    story.relationship_score = max(0, min(100,
                        (story.relationship_score or 50) + effects["relationship_delta"]
                    ))

                # Savepoint makes effects + event creation atomic:
                # if the event flush fails, only this savepoint rolls back —
                # the outer transaction (and all prior ops in advance_story) survive.
                try:
                    async with db.begin_nested():
                        await self._create_game_event(
                            story, "storylet", db,
                            title=tpl["code"].replace("_", " ").title(),
                            content=tpl["narrative"],
                        )
                        await db.flush()
                except Exception as exc:
                    logger.warning(
                        "Storylet %s activation failed, reverting effects: %s",
                        tpl["code"], exc,
                    )
                    story.lifecycle_state = _prev_lifecycle
                    story.relationship_score = _prev_rel_score
                    db.expire(story)
                    continue

                activation = StoryletActivation(
                    storylet_code=tpl["code"],
                    narrative_text=tpl["narrative"],
                    effects=tpl["effects"],
                    priority=tpl["priority"],
                )
                activated.append(activation)
                already_active.add(tpl["code"])

                # ── Persist activation timestamp for cooldown enforcement (Task 1.3) ──
                director = story.director_state or {}
                activations = director.get("storylet_activations", {})
                activations[tpl["code"]] = datetime.now(timezone.utc).isoformat()
                director["storylet_activations"] = activations
                story.director_state = director

        story.active_storylets = list(already_active)
        return activated

    def _check_storylet_preconditions(self, tpl: dict, story: ClientStory, result: SessionResult) -> bool:
        """Check if a storylet's preconditions are met, including cooldown enforcement."""
        pre = tpl["preconditions"]

        # ── Cooldown enforcement (Wave 1, Task 1.3) ──
        cooldown_days = tpl.get("cooldown_days", 0)
        if cooldown_days > 0:
            director = story.director_state or {}
            activations = director.get("storylet_activations", {})
            last_activated = activations.get(tpl["code"])
            if last_activated:
                try:
                    last_dt = datetime.fromisoformat(last_activated)
                    if datetime.now(timezone.utc) - last_dt < timedelta(days=cooldown_days):
                        return False  # Still in cooldown
                except (ValueError, TypeError):
                    pass  # Invalid date — allow activation

        if "lifecycle_state" in pre and story.lifecycle_state != pre["lifecycle_state"]:
            return False
        if "min_calls" in pre and (story.total_calls or 0) < pre["min_calls"]:
            return False
        if "min_debt" in pre:
            debt = (story.memory or {}).get("debt_amount", 0)
            if debt < pre["min_debt"]:
                return False
        if "max_debt" in pre:
            debt = (story.memory or {}).get("debt_amount", 0)
            if debt > pre["max_debt"]:
                return False
        if "min_difficulty" in pre:
            # difficulty is derived from personality_profile, not a direct field
            _profile = story.personality_profile or {}
            _difficulty = _profile.get("difficulty", 5)
            if _difficulty < pre["min_difficulty"]:
                return False
        if "family_status" in pre:
            family = (story.personality_profile or {}).get("family_status", "")
            if family != pre["family_status"]:
                return False

        return True

    # ─── BETWEEN-CALL EVENTS ────────────────────────────

    async def _generate_between_call_events(
        self, story: ClientStory, result: SessionResult, db: AsyncSession
    ) -> list[BetweenCallEvent]:
        """Generate dynamic between-call events using scenario_engine weighted pool.

        Wave 1, Task 1.1: Replaces hardcoded 5-message random.choice() with:
        - 10 weighted events from scenario_engine with archetype/outcome modifiers
        - Dynamic probability scaled by relationship_score and lifecycle_state
        - Typed events (client_message, external_event, storylet_triggered)
        - Client messages generated from event context, not hardcoded strings
        """
        from app.services.scenario_engine import apply_between_calls_context

        events = []
        state = story.lifecycle_state
        rel_score = story.relationship_score or 50.0
        total_calls = story.total_calls or 0

        # ── 1. Generate CRM events from weighted pool ──
        # Only generate if we have at least 1 completed call
        if total_calls >= 1:
            archetype_code = (story.personality_profile or {}).get("archetype", "skeptic")
            existing_events = story.between_call_events if hasattr(story, "between_call_events") else []

            crm_events = apply_between_calls_context(
                call_number=total_calls + 1,
                archetype_code=archetype_code,
                previous_outcome=result.final_emotion_state,
                previous_emotion=result.final_emotion_state,
                existing_events=existing_events if isinstance(existing_events, list) else [],
                relationship_score=rel_score,
                lifecycle_state=state or "FIRST_CONTACT",
                active_storylets=story.active_storylets or [],
                consequence_log=story.consequence_log or [],
            )

            for ce in crm_events:
                event = BetweenCallEvent(
                    event_type="external_event",
                    title=ce.get("description", "Событие"),
                    content=ce.get("description", ""),
                    payload={
                        "event_code": ce.get("event"),
                        "impact": ce.get("impact"),
                        "emotion_shift": ce.get("emotion_shift", {}),
                    },
                )
                events.append(event)
                await self._create_game_event(
                    story, "consequence", db,
                    title=ce.get("description", "Событие"),
                    content=ce.get("description", ""),
                    payload={
                        "event_code": ce.get("event"),
                        "impact": ce.get("impact"),
                    },
                )

        # ── 2. Generate client message based on state + relationship ──
        # Higher relationship = more likely client reaches out
        # States where client would message between calls
        import random
        msg_probability = 0.0
        if state in ("THINKING", "CALLBACK_SCHEDULED"):
            msg_probability = 0.5 + (rel_score / 200)  # 50-100% based on relationship
        elif state in ("INTERESTED", "OBJECTING"):
            msg_probability = 0.3 + (rel_score / 250)  # 30-70%
        elif state == "GHOSTING":
            msg_probability = 0.1  # Low but possible

        if msg_probability > 0 and random.random() < msg_probability:
            # Try LLM-powered message first, fallback to template
            client_msg = None
            try:
                from app.services.between_call_narrator import (
                    generate_client_message_llm,
                    NarratorContext,
                )
                _narrator_ctx = NarratorContext(
                    lifecycle_state=state or "FIRST_CONTACT",
                    relationship_score=rel_score,
                    call_number=total_calls,
                    archetype_code=(story.personality_profile or {}).get("archetype", "skeptic"),
                    client_name=story.story_name or "Клиент",
                    last_outcome=result.final_emotion_state,
                    last_emotion=result.final_emotion_state,
                    last_score=result.score_total,
                    key_memories=[
                        {"content": m} for m in (result.key_moments or [])[:3]
                    ],
                    active_storylets=story.active_storylets or [],
                    between_events=[
                        {"description": e.content} for e in events if e.event_type == "external_event"
                    ],
                )
                client_msg = await generate_client_message_llm(_narrator_ctx)
            except Exception:
                logger.debug("LLM client message generation failed, using template")

            if not client_msg:
                client_msg = self._generate_client_message(state, rel_score, result)

            event = BetweenCallEvent(
                event_type="client_message",
                title="Сообщение от клиента",
                content=client_msg,
            )
            events.append(event)
            await self._create_game_event(
                story, "message", db,
                title="Сообщение от клиента",
                content=client_msg,
            )

        # ── 3. Consequence notifications ──
        for c in (story.consequence_log or []):
            if c.get("is_active") and c.get("level") != CONSEQUENCE_COSMETIC:
                event = BetweenCallEvent(
                    event_type="consequence",
                    title="Последствие",
                    content=c.get("effect_description", ""),
                )
                events.append(event)

        # ── 4. Active storylet reminders ──
        for s_code in (story.active_storylets or []):
            tpl = next((t for t in STORYLET_TEMPLATES if t["code"] == s_code), None)
            if tpl:
                event = BetweenCallEvent(
                    event_type="storylet_triggered",
                    title=tpl["code"].replace("_", " ").title(),
                    content=tpl["narrative"][:200],
                    payload={"storylet_code": s_code, "priority": tpl["priority"]},
                )
                events.append(event)

        return events

    def _generate_client_message(
        self, state: str, rel_score: float, result: SessionResult
    ) -> str:
        """Generate a contextual client message based on state and relationship.

        Messages are grouped by state and modulated by relationship quality.
        """
        import random

        # State-specific message pools with relationship-aware variants
        _messages_by_state = {
            "THINKING": {
                "low_rel": [  # rel < 40
                    "Я подумаю... но не уверен, что это мне нужно.",
                    "Мне нужно больше времени. Пока не звоните.",
                    "А если я просто не буду платить, что будет?",
                ],
                "mid_rel": [  # 40 <= rel < 70
                    "Я поговорил с женой, она беспокоится. Можете ещё раз объяснить про квартиру?",
                    "Сколько точно будет стоить вся процедура?",
                    "Мне друг сказал что банкротство — это позор. Это правда?",
                    "Я прочитал в интернете, что имущество забирают. Это так?",
                ],
                "high_rel": [  # rel >= 70
                    "Спасибо за подробные объяснения. У меня ещё пара вопросов...",
                    "Я обсудил всё с семьёй. Мы склоняемся к тому, чтобы начать процедуру.",
                    "Можете прислать список документов, которые нужно подготовить?",
                ],
            },
            "CALLBACK_SCHEDULED": {
                "low_rel": [
                    "Мне сейчас неудобно разговаривать. Перезвоните позже.",
                    "Я ещё не решил. Не давите на меня.",
                ],
                "mid_rel": [
                    "Спасибо за информацию. Я думаю.",
                    "Жду вашего звонка. Подготовлю вопросы.",
                    "Скажите, а судебный приказ — это плохо? Мне пришло уведомление.",
                ],
                "high_rel": [
                    "Жду звонка! У меня новые вопросы по процедуре.",
                    "Я собрал часть документов. Что ещё нужно?",
                ],
            },
            "INTERESTED": {
                "low_rel": [
                    "А какие гарантии вы даёте?",
                    "Я нашёл другую компанию. Почему у вас дороже?",
                ],
                "mid_rel": [
                    "Расскажите подробнее про сроки процедуры.",
                    "А что будет с моей машиной?",
                ],
                "high_rel": [
                    "Я готов двигаться дальше. Что нужно сделать?",
                    "Спасибо за терпение. Вы очень помогли разобраться.",
                ],
            },
            "OBJECTING": {
                "low_rel": [
                    "Мне всё это не подходит.",
                    "Слишком дорого. У конкурентов дешевле.",
                ],
                "mid_rel": [
                    "Я всё ещё сомневаюсь. Объясните ещё раз про последствия.",
                    "А если банк предложит реструктуризацию?",
                ],
                "high_rel": [
                    "У меня осталось одно сомнение... можем обсудить?",
                ],
            },
            "GHOSTING": {
                "low_rel": [
                    "...",  # Client not responding
                ],
                "mid_rel": [
                    "Извините, был занят. Давайте поговорим позже.",
                ],
                "high_rel": [
                    "Простите, что пропал. Были сложные обстоятельства. Можно продолжить?",
                ],
            },
        }

        state_msgs = _messages_by_state.get(state, _messages_by_state.get("THINKING", {}))

        if rel_score < 40:
            pool = state_msgs.get("low_rel", [])
        elif rel_score < 70:
            pool = state_msgs.get("mid_rel", [])
        else:
            pool = state_msgs.get("high_rel", [])

        if not pool:
            pool = state_msgs.get("mid_rel", ["Спасибо за информацию. Я думаю."])

        return random.choice(pool)

    # ─── HELPER: Create GameClientEvent for CRM ─────────

    async def _create_game_event(
        self, story: ClientStory, event_type: str, db: AsyncSession,
        title: str = "", content: str = "", payload: dict | None = None,
    ) -> None:
        """Create a GameClientEvent for the CRM timeline (Agent 7).

        TZ-1 §11.3 dual-write: also mirrors into the canonical DomainEvent log
        via the shared helper. Going through ``timeline_aggregator.create_game_event``
        keeps the mirror logic in one place.
        """
        _type_map = {
            "call": GameEventType.call,
            "message": GameEventType.message,
            "consequence": GameEventType.consequence,
            "storylet": GameEventType.storylet,
            "status_change": GameEventType.status_change,
            "callback": GameEventType.callback,
        }
        _evt_type = _type_map.get(event_type, GameEventType.consequence)

        from app.services.timeline_aggregator import create_game_event as _create_game_event_shared

        await _create_game_event_shared(
            db,
            story_id=story.id,
            user_id=story.user_id,
            event_type=_evt_type,
            title=title or "Событие",
            source="game_director",
            content=content,
            payload=payload or {},
        )

    # ─── CONVERGENCE ────────────────────────────────────

    async def check_convergence(self, story: ClientStory, db: AsyncSession) -> bool:
        """
        Check if narrative needs bottleneck convergence.
        Triggers: every 3rd call, or relationship_score change > 20, or high-priority storylet.
        """
        if (story.total_calls or 0) % 3 == 0 and (story.total_calls or 0) > 0:
            return True
        # Check for dramatic weight threshold
        active_consequences = sum(
            1 for c in (story.consequence_log or []) if c.get("is_active")
        )
        storylet_priority_sum = sum(
            next((t["priority"] for t in STORYLET_TEMPLATES if t["code"] == s), 0)
            for s in (story.active_storylets or [])
        )
        dramatic_weight = active_consequences * 2 + storylet_priority_sum
        return dramatic_weight > 15

    # ─── PUBLIC API for other agents ────────────────────

    async def get_pending_events(self, story_id: str, db: AsyncSession) -> list[dict]:
        """Get pending between-call events for Agent 7 (CRM) display."""
        result = await db.execute(
            select(GameClientEvent)
            .where(GameClientEvent.story_id == story_id)
            .where(GameClientEvent.is_read == False)
            .order_by(GameClientEvent.created_at.desc())
            .limit(20)
        )
        events = result.scalars().all()
        return [
            {
                "id": str(e.id),
                "type": e.event_type,
                "title": e.title,
                "content": e.content,
                "timestamp": e.created_at.isoformat() if e.created_at else "",
                "payload": e.payload or {},
            }
            for e in events
        ]

    async def get_active_factors(self, story_id: str, db: AsyncSession) -> list[dict]:
        """Get active human factors for Agent 3 (traps) and Agent 4 (voice)."""
        story = await self.load_story(story_id, db)
        if not story:
            return []
        profile = story.personality_profile or {}
        factors = profile.get("human_factors", [])
        return [f for f in factors if f.get("active", False)]

    async def get_relationship_score(self, story_id: str, db: AsyncSession) -> float:
        """Get current relationship score for Agent 5 (gamification)."""
        story = await self.load_story(story_id, db)
        return story.relationship_score if story else 50.0


# ═══════════════════════════════════════════════════════════
# SINGLETON INSTANCE
# ═══════════════════════════════════════════════════════════

game_director = GameDirectorEngine()
