"""roleplay_v2_models

Revision ID: 1377b3c5ac88
Revises: 8bd2c7a674ea
Create Date: 2026-03-18 21:28:30.185738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1377b3c5ac88'
down_revision: Union[str, None] = '8bd2c7a674ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archetype_code', sa.String(length=50), nullable=False),
    sa.Column('transition_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_severity', sa.Integer(), nullable=False),
    sa.Column('breaking_point', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('initial_state', sa.String(length=50), nullable=False),
    sa.Column('max_state_first_call', sa.String(length=50), nullable=False),
    sa.Column('fake_transitions', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archetype_code')
    )
    op.create_table('objection_chains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profession_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('budget', 'government', 'military', 'pensioner', 'entrepreneur', 'worker', 'it_office', 'trade_service', 'homemaker', 'special', name='professioncategory'), nullable=False),
    sa.Column('typical_debt_min', sa.Integer(), nullable=False),
    sa.Column('typical_debt_max', sa.Integer(), nullable=False),
    sa.Column('legal_literacy', sa.Integer(), nullable=False),
    sa.Column('vocabulary_level', sa.String(length=50), nullable=False),
    sa.Column('specific_fears', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('specific_objections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('speech_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('traps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('client_phrase', sa.Text(), nullable=False),
    sa.Column('wrong_response_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_response_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_response_example', sa.Text(), nullable=True),
    sa.Column('penalty', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('archetype_code', sa.String(length=50), nullable=False),
    sa.Column('profession_id', sa.UUID(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=False),
    sa.Column('legal_literacy', sa.Integer(), nullable=False),
    sa.Column('total_debt', sa.Integer(), nullable=False),
    sa.Column('creditors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('income_type', sa.String(length=50), nullable=False),
    sa.Column('property_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fears', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('soft_spot', sa.Text(), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=False),
    sa.Column('resistance_level', sa.Integer(), nullable=False),
    sa.Column('lead_source', sa.String(length=50), nullable=False),
    sa.Column('call_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('crm_notes', sa.Text(), nullable=True),
    sa.Column('hidden_objections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trap_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chain_id', sa.UUID(), nullable=True),
    sa.Column('breaking_point', sa.Text(), nullable=True),
    sa.Column('trap_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['objection_chains.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['profession_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_profiles')
    op.drop_table('traps')
    op.drop_table('profession_profiles')
    op.drop_table('objection_chains')
    op.drop_table('emotion_profiles')
    # ### end Alembic commands ###
