"""add_preferences_onboarding_5state_emotion

Revision ID: 8bd2c7a674ea
Revises: c3f1a2b45d67
Create Date: 2026-03-18 16:48:12.180476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bd2c7a674ea'
down_revision: Union[str, None] = 'c3f1a2b45d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Expand EmotionState enum: cold, warming, open → cold, skeptical, warming, open, deal
    op.execute("ALTER TYPE emotionstate ADD VALUE IF NOT EXISTS 'skeptical' AFTER 'cold'")
    op.execute("ALTER TYPE emotionstate ADD VALUE IF NOT EXISTS 'deal' AFTER 'open'")

    op.add_column('training_sessions', sa.Column('score_anti_patterns', sa.Float(), nullable=True))
    op.drop_column('training_sessions', 'score_emotional')
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'preferences')
    op.add_column('training_sessions', sa.Column('score_emotional', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('training_sessions', 'score_anti_patterns')
    # ### end Alembic commands ###
