import { create } from "zustand";
import { api } from "@/lib/api";
import type { PvPRating, PvPDuel, DuelBrief, PvPLeaderboardEntry, PvPSeason, PvPRankTier } from "@/types";
import { normalizeRankTier } from "@/types";
import { logger } from "@/lib/logger";

type QueueStatus = "idle" | "searching" | "matched" | "in_duel";

interface PvPMessage {
  id: string;
  sender_role: "seller" | "client";
  text: string;
  round: number;
  timestamp: string;
  // Issue #167 — server-confirmed identifier from PR #117 backend echo.
  // ``server_msg_id`` is the canonical id once the server has accepted
  // the message; we use it as the React key so optimistic→confirmed
  // reconciliation does not remount the bubble. ``client_msg_id`` is
  // generated by the sender and round-tripped on the echo so we can
  // pair the optimistic row to the server's confirmation.
  server_msg_id?: string;
  client_msg_id?: string;
  // ``true`` when the message exists only as an optimistic local
  // render — no server echo received yet.
  pending?: boolean;
}

interface JudgeScore {
  selling_score: number;
  acting_score: number;
  legal_accuracy: number;
}

export interface PlayerBreakdown {
  selling_score: number;
  acting_score: number;
  legal_score: number;
  total: number;
  selling_breakdown?: Record<string, number>;
  acting_breakdown?: Record<string, number>;
  legal_details?: { claim: string; accuracy: string; explanation: string }[];
  best_reply?: string;
  recommendations?: string[];
  flags?: string[];
}

interface DuelResult {
  duel_id: string;
  player1_total: number;
  player2_total: number;
  winner_id: string | null;
  is_draw: boolean;
  is_pve: boolean;
  rating_change_applied: boolean;
  player1_rating_delta: number;
  player2_rating_delta: number;
  summary: string;
  player1_breakdown?: PlayerBreakdown | null;
  player2_breakdown?: PlayerBreakdown | null;
  turning_point?: { round?: number; description?: string } | null;
}

interface PvPState {
  // Rating
  rating: PvPRating | null;
  ratingLoading: boolean;

  // Queue
  queueStatus: QueueStatus;
  queuePosition: number;
  estimatedWait: number;
  matchedOpponentRating: number | null;

  // Duel
  // PR-cleanup (2026-05-05): removed `pvEOffer` and `currentDuel` —
  // both written-only with no consumer. The PvE-offer modal was deleted
  // 2026-04-XX (see comment in pvp/page.tsx) and the case "pve.offer"
  // WS handler now no-ops; `currentDuel` was never assigned anywhere.
  duelBrief: DuelBrief | null;
  myRole: "seller" | "client" | null;
  roundNumber: number;
  timeRemaining: number;
  messages: PvPMessage[];
  judgeScore: JudgeScore | null;
  duelResult: DuelResult | null;

  // History
  myDuels: PvPDuel[];
  duelsLoading: boolean;

  // Season
  activeSeason: PvPSeason | null;

  // Leaderboard
  leaderboard: PvPLeaderboardEntry[];
  leaderboardTotal: number;
  leaderboardLoading: boolean;

  // Actions
  fetchRating: (ratingType?: string) => Promise<void>;
  fetchMyDuels: () => Promise<void>;
  fetchLeaderboard: (tier?: string, limit?: number) => Promise<void>;
  fetchActiveSeason: () => Promise<void>;
  setQueueStatus: (status: QueueStatus) => void;
  setQueuePosition: (pos: number, est: number) => void;
  setMatchedOpponentRating: (rating: number | null) => void;
  resetQueue: () => void;
  setDuelBrief: (brief: DuelBrief) => void;
  setMyRole: (role: "seller" | "client") => void;
  setRoundNumber: (n: number) => void;
  setTimeRemaining: (t: number) => void;
  addMessage: (msg: PvPMessage) => void;
  replaceMessages: (messages: PvPMessage[]) => void;
  setJudgeScore: (score: JudgeScore) => void;
  setDuelResult: (result: DuelResult) => void;
  resetDuel: () => void;
  _msgCounter: number;
  nextMsgId: () => string;
}

export const usePvPStore = create<PvPState>((set, get) => ({
  rating: null,
  ratingLoading: false,
  queueStatus: "idle",
  queuePosition: 0,
  estimatedWait: 0,
  matchedOpponentRating: null,
  duelBrief: null,
  myRole: null,
  roundNumber: 0,
  timeRemaining: 600,
  messages: [],
  judgeScore: null,
  duelResult: null,
  myDuels: [],
  duelsLoading: false,
  activeSeason: null,
  leaderboard: [],
  leaderboardTotal: 0,
  leaderboardLoading: false,
  _msgCounter: 0,

  fetchRating: async (ratingType?: string) => {
    set({ ratingLoading: true });
    try {
      const params = ratingType ? `?rating_type=${ratingType}` : "";
      const data = await api.get(`/pvp/rating/me${params}`);
      if (data && typeof data.rank_tier === "string") {
        data.rank_tier = normalizeRankTier(data.rank_tier);
      }
      if (data && typeof data.peak_tier === "string") {
        data.peak_tier = normalizeRankTier(data.peak_tier);
      }
      set({ rating: data, ratingLoading: false });
    } catch (err) {
      logger.warn("[PvP] Failed to fetch rating:", err);
      // Keep rating=null so UI can distinguish "failed to load" from real data.
      // Using default 1500/Iron would mislead users who actually have a real rating.
      set({ rating: null, ratingLoading: false });
    }
  },

  fetchMyDuels: async () => {
    set({ duelsLoading: true });
    try {
      // PR-9 (2026-05-07): exclude cancelled / reaper-killed duels.
      // They aren't a loss in Glicko (bookkeeper guards that) — only a
      // visual artifact. PR-3 muted the colour; PR-9 hides them entirely.
      const data = await api.get("/pvp/duels/me?limit=20&exclude_cancelled=true");
      set({ myDuels: Array.isArray(data) ? data : [], duelsLoading: false });
    } catch {
      set({ duelsLoading: false });
    }
  },

  fetchLeaderboard: async (tier, limit = 50) => {
    set({ leaderboardLoading: true });
    try {
      const params = new URLSearchParams({ limit: String(limit) });
      if (tier && tier !== "all") params.set("tier", tier);
      const data = await api.get(`/pvp/leaderboard?${params}`);
      set({
        leaderboard: data.entries || [],
        leaderboardTotal: data.total_players || 0,
        leaderboardLoading: false,
      });
    } catch {
      set({ leaderboardLoading: false });
    }
  },

  fetchActiveSeason: async () => {
    try {
      const data = await api.get("/pvp/season/active");
      set({ activeSeason: data || null });
    } catch (err) {
      logger.warn("[PvP] Failed to fetch active season:", err);
      set({ activeSeason: null });
    }
  },

  setQueueStatus: (queueStatus) => set({ queueStatus }),
  setQueuePosition: (queuePosition, estimatedWait) => set({ queuePosition, estimatedWait }),
  setMatchedOpponentRating: (matchedOpponentRating) => set({ matchedOpponentRating }),
  resetQueue: () => set({
    queueStatus: "idle",
    queuePosition: 0,
    estimatedWait: 0,
    matchedOpponentRating: null,
  }),
  setDuelBrief: (duelBrief) => set({ duelBrief, queueStatus: "in_duel" }),
  setMyRole: (myRole) => set({ myRole }),
  setRoundNumber: (roundNumber) => set({ roundNumber }),
  setTimeRemaining: (timeRemaining) => set({ timeRemaining }),
  // Issue #167 — dedup-aware add. Three reconciliation rules:
  //   1. server_msg_id already in state → drop (reconnect-resume race).
  //   2. client_msg_id matches optimistic pending row → upgrade in place.
  //   3. otherwise → append.
  addMessage: (msg) => set((s) => {
    const sid = msg.server_msg_id;
    const cid = msg.client_msg_id;
    if (sid && s.messages.some((m) => m.server_msg_id === sid)) {
      return { messages: s.messages };
    }
    if (cid) {
      const idx = s.messages.findIndex((m) => m.client_msg_id === cid && m.pending);
      if (idx >= 0) {
        const next = s.messages.slice();
        next[idx] = {
          ...next[idx],
          ...msg,
          id: sid ?? next[idx].id,
          pending: false,
        };
        return { messages: next.slice(-500) };
      }
    }
    const finalMsg = sid ? { ...msg, id: sid } : msg;
    return { messages: [...s.messages, finalMsg].slice(-500) };
  }),
  replaceMessages: (messages) => set({ messages }),
  setJudgeScore: (judgeScore) => set({ judgeScore }),
  setDuelResult: (duelResult) => set({ duelResult }),
  resetDuel: () => set({
    queueStatus: "idle",
    queuePosition: 0,
    estimatedWait: 0,
    matchedOpponentRating: null,
    duelBrief: null,
    myRole: null,
    roundNumber: 0,
    timeRemaining: 600,
    messages: [],
    judgeScore: null,
    duelResult: null,
  }),
  nextMsgId: () => {
    const c = get()._msgCounter + 1;
    set({ _msgCounter: c });
    return `pvp-${c}`;
  },
}));
